### ISSUE TITLE
1.0.1: `/poll` command should not lose work

### ISSUE THREAD

**Issue by lkraav** [matterpoll/matterpoll#101]
#### Summary
If you write `/poll` command invalid input, all work invested is lost post-submit.

#### Steps to reproduce
1. Type `/poll "Something or other" yes no maybe`, submit
2. Confirm response "Invalid input: Unrecognised poll setting yes no maybe"
3. Try to get your `/poll` input back from history, you can't

#### Expected behavior
Input submitted should be displayed w/ validation error message.

#### Observed behavior (that appears unintentional)
Only validation error message is displayed. No way to recover work.

#### Server configuration
Linux

**Mattermost version:**
5.4.0

**Matterpoll version:**
1.0.1

**Comment by hanzei** [comment]
Thank for the report @lkraav. This is relative easy to improve.
