### ISSUE TITLE
Shutdown plugin if site URL is not set

### ISSUE THREAD

**Issue by hanzei** [matterpoll/matterpoll#110]
Since Matterpoll needs the the site URL to properly work, the plugin could shutdown if site URL is not set. 

If we want this behaviour, how do we accomplish it? We could:
- `panic`
- Return an error in `OnConfigurationChange()` and call `OnConfigurationChange()` in `OnActivate()`

@kaakaa thoughts?

**Comment by kaakaa** [comment]
There is no differences for admins and users, so I'm fine with the both. I'm prefer checking in `OnConfigurationChange`, because it looks more polite for me.

**Comment by hanzei** [comment]
The is currently some discussion about that to do if `OnConfigurationChange` returns an error. https://community.mattermost.com/core/pl/1cioqbc8yidhumh6f3nxom6kky

I propose to wait until the dust has settled down.
