### ISSUE TITLE
Update the help text to show "" vs [] for command params

### ISSUE THREAD

**Issue by mkdbns** [matterpoll/matterpoll#113]
#### Summary
The current hint text is misleading/confusing to users as it leads them to think that the parameters should be in [] vs ""

#### Steps to reproduce
1. Type /poll to see the hint text

#### Expected behavior
Users would benefit from seeing the following hint: 

> /poll "Question" "Answer 1" "Answer 2" ...

instead of

> /poll [Question] [Answer 1] [Answer 2] ...

#### Observed behavior (that appears unintentional)
What did you see happen? Please include relevant error messages and/or screenshots.

#### Server configuration
**Operating system:**
Any
**Mattermost version:**
Any
**Matterpoll version:**
Latest
**Updated from an older Matterpoll version or fresh install:**
Fresh install
<details>
<summary>Mattermost server logs</summary>

```
Insert your Mattermost server logs here
```
</details>

**Comment by kaakaa** [comment]
Good catching @mkdbns, thank you!

**Comment by mkdbns** [comment]
Thanks so much for fixing this issue. When do you think there will be another official release?
