### ISSUE TITLE
Buttons "End poll" and "Delete Poll" should be use for everyone

### ISSUE THREAD

**Issue by lxm065** [matterpoll/matterpoll#118]
#### Summary

The creater is a bot,but in the end ,it must be end by someone who is not creater or admin.

and sometimes , someone forget to end it.
or add a --deadline 1day ,so it can end itself.

#### Describe alternatives you've considered

Add a Poll Settings,such as --deleteable to make it flexible.

#### Additional context

![image pasted at 2018-12-5 13-57](https://user-images.githubusercontent.com/10704744/49493109-c0026c80-f895-11e8-8bce-083a5b65c2f5.png)

**Comment by hanzei** [comment]
I see this as a very special use case. Sure, ending scheduled polls in one, but I can't think of another. I would rather not a another Poll Setting for just one use case.

>  or add a --deadline 1day ,so it can end itself.

Take a look at #95 for this.

**Comment by lxm065** [comment]
> I see this as a very special use case. Sure, ending scheduled polls in one, but I can't think of another. I would rather not a another Poll Setting for just one use case.
> 
> > or add a --deadline 1day ,so it can end itself.
> 
> Take a look at #95 for this.

ok,i will follow it，3q

**Comment by hanzei** [comment]
Closing in favour of #95
