### ISSUE TITLE
Add linebreak after Voting Buttons

### ISSUE THREAD

**Issue by hanzei** [matterpoll/matterpoll#121]
As proposed by Mike Gamble [here](https://community.mattermost.com/core/pl/5p17es6k8frnbgr3szeugwmm8w) we should add a break between the Voting Buttons and Management Buttons. 

We could do this via server side by adding two different `SlackAttachments`. This would look like this:

![screenshot from 2018-12-03 10-31-03](https://user-images.githubusercontent.com/16541325/49592068-78044800-f970-11e8-961b-15f7e3be3050.png)

Or we could do it via webapp.

**Comment by hanzei** [comment]
I asked also asked @mike_gamble for feedback https://community-daily.mattermost.com/core/pl/xe9fzshrt7r5xxy1k75k7r7ddr

**Comment by hanzei** [comment]
@kaakaa Do you think this can be handled via webapp code?

**Comment by kaakaa** [comment]
I think that if this issue is the problem about visibility between vote buttons and management button, it would be resolved by #267. Additionally, #234 also resolve the problem about visibility.

Should we tackle this issue if #267 is resolved?
