### ISSUE TITLE
Use Bot Account

### ISSUE THREAD

**Issue by hanzei** [matterpoll/matterpoll#126]
#### Summary

5.8 will introduce Bot Accounts to Mattermost. We should make use of this. The changes I propose are:
- Create a Bot Account "Matterpoll" on activation 
- Store the userId in the KV Store
- Create all posts with this user.

#### Additional context

Link to spec: https://docs.google.com/document/d/139dNmjHz0Tflcgby85xaJtxYwapPctZHiZpZT6aS0DA

**Comment by hanzei** [comment]
@kaakaa Toughs on this one?

**Comment by kaakaa** [comment]
@hanzei 
I like this feature. It's great to introduce bot without user's manual operations.

But I have only one concern for now.
[ExecuteCommand method](https://github.com/matterpoll/matterpoll/blob/master/server/plugin/command.go#L32) just returns `model.CommandResponse`, not creates posts. So we can't inject userId of bot account to posts created by `/poll` command.
Do we solve this issue by calling `p.API.CreatePost` in ExecuteCommand` method? or are there any other solutions?

**Comment by hanzei** [comment]
> Do we solve this issue by calling `p.API.CreatePost` in ExecuteCommand` method?

I would do exactly this.
