### ISSUE TITLE
Parse emojis in option buttons 

### ISSUE THREAD

**Issue by rubdottocom** [matterpoll/matterpoll#127]
Would be awesome to add emoji on the options.

Something like:
`
/poll "Is matterpoll awesome?" ":+1: of course!" ":-1: so so"`

will be rendered as

`Is matterpoll awesome? [👍 of course!] [👎 so so]`

**Comment by hanzei** [comment]
HW ticket for this is https://github.com/mattermost/mattermost-server/issues/10290, if someone want to pick this up

**Comment by hanzei** [comment]
This will be fixed with Mattermost 5.10.
