### ISSUE TITLE
After create pool, buttons dont working

### ISSUE THREAD

**Issue by radoslavius** [matterpoll/matterpoll#128]
#### Summary
After create pool, buttons dont working.

#### Observed behavior (that appears unintentional)
It does nothing. Error in console

#### Server configuration
**Operating system:** Ubuntu 18.04.1 LTS

**Mattermost version:** 5.7.0

**Matterpoll version:** v1.0.3

**Updated from an older Matterpoll version or fresh install:** fresh install

**Mattermost server logs**
```
{"level":"error","ts":1548261921.999396,"caller":"web/context.go:60","msg":"Action integration error","path":"/api/v4/posts/dcnwi7zkwifwzkxbd6iunt9aho/actions/1axtunpptibpxb8hfzti8z8yqr","request_id":"c1g8f7n5kpd15bt8jk98cfy6na","ip_addr":"172.16.2.3","user_id":"edc77zsz5jfj8yya969swm5huy","method":"POST","err_where":"DoActionRequest","http_code":400,"err_details":"status=405"}
```

**Comment by hanzei** [comment]
@radoslavius Thanks for the detailed report. Do you see any other related log messages? Could you please run the server with log level `debug` and check again?

**Comment by radoslavius** [comment]
@hanzei Before you wrote questions I tried set correct url in mattermost configuration from http to https (site is working on https and https doing nginx, not mattermost) and restart it and disable and reenable plugin and now poll is working as described.
Thanks for your quick response
