### ISSUE TITLE
hyperlinks in questions

### ISSUE THREAD

**Issue by ibourgeois** [matterpoll/matterpoll#129]
#### Summary

The ability to create hyperlinks in the questions.

#### Describe alternatives you've considered

Forking. PR. Copy+Paste

#### Additional context

Everything works as expected, thanks! We just aren't able to create links in our questions. We can put a URL in the question, but we have to copy that URL (or right click + visit) instead of just clicking. lazy. i know. lol

**Comment by hanzei** [comment]
Hey @ibourgeois,

Thanks for reporting this. Rendering links in message buttons isn't supported in Mattermost in the moment. Would you please open a ticket on [mattermost.uservoice.com](https://mattermost.uservoice.com)? Or would you even be open to fixing this my yourself?

**Comment by hanzei** [comment]
HW ticket for this is https://github.com/mattermost/mattermost-server/issues/10292, if someone want to pick this up

**Comment by hanzei** [comment]
This will be fixed with Mattermost 5.10.
