### ISSUE TITLE
Pinned polls get unpinned on a vote

### ISSUE THREAD

**Issue by t1nux** [matterpoll/matterpoll#130]
#### Summary
We have many very active channels, which is why I typically pin polls, so that everyone has quick access to them. However, when someone votes, the post get unpinned.

#### Steps to reproduce
1. make a poll
2. pin the poll
3. vote

#### Expected behavior
The poll should remain pinned.

#### Observed behavior (that appears unintentional)
The poll is not pinned anymore.

#### Server configuration
**Operating system:**
Arch Linux
**Mattermost version:**
5.7.0
**Matterpoll version:**
1.0.3
**Updated from an older Matterpoll version or fresh install:**
Fresh install

**Comment by hanzei** [comment]
Good catch @t1nux! I can reproduce the issue and will work on a fix.

**Comment by hanzei** [comment]
I investigated into this problem and it seams to be a bug in the Mattermost Server. I posted a bug report in https://community-daily.mattermost.com/core/pl/pcarbbsj3pnp5c3o3i7oqqkh4o.

**Comment by hanzei** [comment]
This is a bug in the Mattermost Server. Leaving this issue open for visibility.

**Comment by hanzei** [comment]
This is fixed with Mattermost `v5.11.0`.
