### ISSUE TITLE
Problem posting poll

### ISSUE THREAD

**Issue by LukasFir** [matterpoll/matterpoll#135]
#### Summary
Publish poll fails

#### Steps to reproduce
1. Entering **_/poll_** and a question
2. Trying to post poll

#### Expected behavior
Poll should be published.

#### Observed behavior (that appears unintentional)
It's not possible to post poll. 

Following error is displayed: 
Command with a trigger of '/poll' not found. 
![Poll1](https://user-images.githubusercontent.com/48556338/54534103-fb7bff00-498b-11e9-9db6-7d1d2479e1d1.jpg)

The default command was not changed. Typing '/ poll' also displays a preview of a survey above the command.
![Poll2](https://user-images.githubusercontent.com/48556338/54534114-0171e000-498c-11e9-9b2f-54273d6c7497.jpg)

#### Server configuration
**Operating system: Ubuntu 18.04**

**Mattermost version: 5.9.0**

**Matterpoll version: 1.0.3**

**Matterpoll fresh install**

###Log
{"level":"error","ts":1552915316.304616,"caller":"plugin/client_rpc_generated.go:104","msg":"RPC call ExecuteCommand to plugin failed.","plugin_id":"com.github.matterpoll.matterpoll","error":"unexpected EOF"}

**Comment by hanzei** [comment]
After setting the log level to debug, are there other related log messages?

**Comment by LukasFir** [comment]
Then I get following messages:

{"level":"error","ts":1552918378.7885025,"caller":"plugin/client_rpc_generated.go:67","msg":"RPC call OnConfigurationChange to plugin failed.","plugin_id":"com.github.matterpoll.matterpoll","error":"connection is shut down"}
{"level":"error","ts":1552918378.8343883,"caller":"plugin/client_rpc_generated.go:67","msg":"RPC call OnConfigurationChange to plugin failed.","plugin_id":"com.github.matterpoll.matterpoll","error":"connection is shut down"}
{"level":"error","ts":1552918390.8890758,"caller":"plugin/client_rpc_generated.go:104","msg":"RPC call ExecuteCommand to plugin failed.","plugin_id":"com.github.matterpoll.matterpoll","error":"connection is shut down"}
{"level":"info","ts":1552918450.5582335,"caller":"scheduler/worker.go:78","msg":"Worker: Job is complete","worker":"Plugins","job_id":"c4akh6qk7iypuqzpu1jo78w8py"}
{"level":"error","ts":1552918465.4616377,"caller":"plugin/client_rpc_generated.go:104","msg":"RPC call ExecuteCommand to plugin failed.","plugin_id":"com.github.matterpoll.matterpoll","error":"connection is shut down"}

**Comment by LukasFir** [comment]
**The server is set up as follows:**

"PluginSettings": {
        "Enable": true,
        "EnableUploads": true,
        "Directory": "./plugins",
        "ClientDirectory": "./client/plugins",
        "Plugins": {},
        "PluginStates": {
            "com.github.matterpoll.matterpoll": {
                "Enable": true
            }
        }
    },

**Comment by LukasFir** [comment]
{"level":"debug","ts":1553684137.8163705,"caller":"go-plugin/client.go:844","msg":"panic: runtime error: invalid memory address or nil pointer dereference","plugin_id":"com.github.matterpoll.matterpoll"}
{"level":"debug","ts":1553684137.8164802,"caller":"go-plugin/client.go:844","msg":"[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x9d4261]","plugin_id":"com.github.matterpoll.matterpoll"}
{"level":"debug","ts":1553684137.816529,"caller":"go-plugin/client.go:844","msg":"","plugin_id":"com.github.matterpoll.matterpoll"}
{"level":"debug","ts":1553684137.8165884,"caller":"go-plugin/client.go:844","msg":"goroutine 40 [running]:","plugin_id":"com.github.matterpoll.matterpoll"}
{"level":"debug","ts":1553684137.8166335,"caller":"go-plugin/client.go:844","msg":"github.com/matterpoll/matterpoll/server/plugin.(*MatterpollPlugin).ExecuteCommand(0xc0001168a0, 0xc000126c00, 0xc00032c120, 0x7f62db2d1050, 0xc0001168a0)","plugin_id":"com.github.matterpoll.matterpoll"}
{"level":"debug","ts":1553684137.8166919,"caller":"go-plugin/client.go:844","msg":"\t/home/travis/gopath/src/github.com/matterpoll/matterpoll/server/plugin/command.go:33 +0x61","plugin_id":"com.github.matterpoll.matterpoll"}
{"level":"debug","ts":1553684137.8167367,"caller":"go-plugin/client.go:844","msg":"github.com/matterpoll/matterpoll/server/vendor/github.com/mattermost/mattermost-server/plugin.(*hooksRPCServer).ExecuteCommand(0xc000132e00, 0xc0001268d0, 0xc000126c50, 0x0, 0x0)","plugin_id":"com.github.matterpoll.matterpoll"}
{"level":"debug","ts":1553684137.816788,"caller":"go-plugin/client.go:844","msg":"\t/home/travis/gopath/src/github.com/matterpoll/matterpoll/server/vendor/github.com/mattermost/mattermost-server/plugin/client_rpc_generated.go:114 +0x7b","plugin_id":"com.github.matterpoll.matterpoll"}
{"level":"debug","ts":1553684137.8169122,"caller":"go-plugin/client.go:844","msg":"reflect.Value.call(0xc000122660, 0xc000128058, 0x13, 0xb5d5af, 0x4, 0xc00009bf18, 0x3, 0x3, 0xc00011e600, 0x0, ...)","plugin_id":"com.github.matterpoll.matterpoll"}
{"level":"debug","ts":1553684137.8169575,"caller":"go-plugin/client.go:844","msg":"\t/home/travis/.gimme/versions/go1.11.2.linux.amd64/src/reflect/value.go:447 +0x449","plugin_id":"com.github.matterpoll.matterpoll"}
{"level":"debug","ts":1553684137.8170414,"caller":"go-plugin/client.go:844","msg":"reflect.Value.Call(0xc000122660, 0xc000128058, 0x13, 0xc00003bf18, 0x3, 0x3, 0x0, 0x0, 0x0)","plugin_id":"com.github.matterpoll.matterpoll"}
{"level":"debug","ts":1553684137.8170898,"caller":"go-plugin/client.go:844","msg":"\t/home/travis/.gimme/versions/go1.11.2.linux.amd64/src/reflect/value.go:308 +0xa4","plugin_id":"com.github.matterpoll.matterpoll"}
{"level":"debug","ts":1553684137.817132,"caller":"go-plugin/client.go:844","msg":"net/rpc.(*service).call(0xc00011e1c0, 0xc00021c140, 0xc000290188, 0xc0002901b0, 0xc000218280, 0xc00012a5e0, 0xa26960, 0xc0001268d0, 0x16, 0xa269a0, ...)","plugin_id":"com.github.matterpoll.matterpoll"}
{"level":"debug","ts":1553684137.8171747,"caller":"go-plugin/client.go:844","msg":"\t/home/travis/.gimme/versions/go1.11.2.linux.amd64/src/net/rpc/server.go:384 +0x14e","plugin_id":"com.github.matterpoll.matterpoll"}
{"level":"debug","ts":1553684137.8172157,"caller":"go-plugin/client.go:844","msg":"created by net/rpc.(*Server).ServeCodec","plugin_id":"com.github.matterpoll.matterpoll"}
{"level":"debug","ts":1553684137.8172557,"caller":"go-plugin/client.go:844","msg":"\t/home/travis/.gimme/versions/go1.11.2.linux.amd64/src/net/rpc/server.go:481 +0x47e","plugin_id":"com.github.matterpoll.matterpoll"}
{"level":"error","ts":1553684137.8187282,"caller":"plugin/client_rpc_generated.go:104","msg":"RPC call ExecuteCommand to plugin failed.","plugin_id":"com.github.matterpoll.matterpoll","error":"unexpected EOF"}
{"level":"debug","ts":1553684137.8192008,"caller":"go-plugin/client.go:595","msg":"plugin process exited","plugin_id":"com.github.matterpoll.matterpoll","wrapped_extras":"pathplugins/com.github.matterpoll.matterpoll/server/dist/plugin-linux-amd64pid18798errorexit status 2"}
{"level":"debug","ts":1553684137.8202274,"caller":"web/context.go:76","msg":"Command with a trigger of 'poll' not found. To send a message beginning with \"/\", try adding an empty space at the beginning of the message.","path":"/api/v4/commands/execute","request_id":"qxbhd4ywgpd65xrtukkkmbedge","ip_addr":"180.100.190.43","user_id":"rfo6yi55gpfiirxjtx1wg91bro","method":"POST","err_where":"command","http_code":404,"err_details":""}

**Comment by LukasFir** [comment]
When setting the log level to debug, I receive the following messages:

{"level":"debug","ts":1553684137.8163705,"caller":"go-plugin/client.go:844","msg":"panic: runtime error: invalid memory address or nil pointer dereference","plugin_id":"com.github.matterpoll.matterpoll"}
{"level":"debug","ts":1553684137.8164802,"caller":"go-plugin/client.go:844","msg":"[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x9d4261]","plugin_id":"com.github.matterpoll.matterpoll"}
{"level":"debug","ts":1553684137.816529,"caller":"go-plugin/client.go:844","msg":"","plugin_id":"com.github.matterpoll.matterpoll"}
{"level":"debug","ts":1553684137.8165884,"caller":"go-plugin/client.go:844","msg":"goroutine 40 [running]:","plugin_id":"com.github.matterpoll.matterpoll"}
{"level":"debug","ts":1553684137.8166335,"caller":"go-plugin/client.go:844","msg":"github.com/matterpoll/matterpoll/server/plugin.(*MatterpollPlugin).ExecuteCommand(0xc0001168a0, 0xc000126c00, 0xc00032c120, 0x7f62db2d1050, 0xc0001168a0)","plugin_id":"com.github.matterpoll.matterpoll"}
{"level":"debug","ts":1553684137.8166919,"caller":"go-plugin/client.go:844","msg":"\t/home/travis/gopath/src/github.com/matterpoll/matterpoll/server/plugin/command.go:33 +0x61","plugin_id":"com.github.matterpoll.matterpoll"}
{"level":"debug","ts":1553684137.8167367,"caller":"go-plugin/client.go:844","msg":"github.com/matterpoll/matterpoll/server/vendor/github.com/mattermost/mattermost-server/plugin.(*hooksRPCServer).ExecuteCommand(0xc000132e00, 0xc0001268d0, 0xc000126c50, 0x0, 0x0)","plugin_id":"com.github.matterpoll.matterpoll"}
{"level":"debug","ts":1553684137.816788,"caller":"go-plugin/client.go:844","msg":"\t/home/travis/gopath/src/github.com/matterpoll/matterpoll/server/vendor/github.com/mattermost/mattermost-server/plugin/client_rpc_generated.go:114 +0x7b","plugin_id":"com.github.matterpoll.matterpoll"}
{"level":"debug","ts":1553684137.8169122,"caller":"go-plugin/client.go:844","msg":"reflect.Value.call(0xc000122660, 0xc000128058, 0x13, 0xb5d5af, 0x4, 0xc00009bf18, 0x3, 0x3, 0xc00011e600, 0x0, ...)","plugin_id":"com.github.matterpoll.matterpoll"}
{"level":"debug","ts":1553684137.8169575,"caller":"go-plugin/client.go:844","msg":"\t/home/travis/.gimme/versions/go1.11.2.linux.amd64/src/reflect/value.go:447 +0x449","plugin_id":"com.github.matterpoll.matterpoll"}
{"level":"debug","ts":1553684137.8170414,"caller":"go-plugin/client.go:844","msg":"reflect.Value.Call(0xc000122660, 0xc000128058, 0x13, 0xc00003bf18, 0x3, 0x3, 0x0, 0x0, 0x0)","plugin_id":"com.github.matterpoll.matterpoll"}
{"level":"debug","ts":1553684137.8170898,"caller":"go-plugin/client.go:844","msg":"\t/home/travis/.gimme/versions/go1.11.2.linux.amd64/src/reflect/value.go:308 +0xa4","plugin_id":"com.github.matterpoll.matterpoll"}
{"level":"debug","ts":1553684137.817132,"caller":"go-plugin/client.go:844","msg":"net/rpc.(*service).call(0xc00011e1c0, 0xc00021c140, 0xc000290188, 0xc0002901b0, 0xc000218280, 0xc00012a5e0, 0xa26960, 0xc0001268d0, 0x16, 0xa269a0, ...)","plugin_id":"com.github.matterpoll.matterpoll"}
{"level":"debug","ts":1553684137.8171747,"caller":"go-plugin/client.go:844","msg":"\t/home/travis/.gimme/versions/go1.11.2.linux.amd64/src/net/rpc/server.go:384 +0x14e","plugin_id":"com.github.matterpoll.matterpoll"}
{"level":"debug","ts":1553684137.8172157,"caller":"go-plugin/client.go:844","msg":"created by net/rpc.(*Server).ServeCodec","plugin_id":"com.github.matterpoll.matterpoll"}
{"level":"debug","ts":1553684137.8172557,"caller":"go-plugin/client.go:844","msg":"\t/home/travis/.gimme/versions/go1.11.2.linux.amd64/src/net/rpc/server.go:481 +0x47e","plugin_id":"com.github.matterpoll.matterpoll"}
{"level":"error","ts":1553684137.8187282,"caller":"plugin/client_rpc_generated.go:104","msg":"RPC call ExecuteCommand to plugin failed.","plugin_id":"com.github.matterpoll.matterpoll","error":"unexpected EOF"}
{"level":"debug","ts":1553684137.8192008,"caller":"go-plugin/client.go:595","msg":"plugin process exited","plugin_id":"com.github.matterpoll.matterpoll","wrapped_extras":"pathplugins/com.github.matterpoll.matterpoll/server/dist/plugin-linux-amd64pid18798errorexit status 2"}
{"level":"debug","ts":1553684137.8202274,"caller":"web/context.go:76","msg":"Command with a trigger of 'poll' not found. To send a message beginning with "/", try adding an empty space at the beginning of the message.","path":"/api/v4/commands/execute","request_id":"qxbhd4ywgpd65xrtukkkmbedge","ip_addr":"180.100.190.43","user_id":"rfo6yi55gpfiirxjtx1wg91bro","method":"POST","err_where":"command","http_code":404,"err_details":""}

**Comment by hanzei** [comment]
Did you set a [Site URL](https://docs.mattermost.com/administration/config-settings.html#site-url) for your Mattermost Server?

**Comment by LukasFir** [comment]
No, the Site URL was not configured yet. After I did that, everything worked. Thank you very much.

**Comment by hanzei** [comment]
No problem. Glad we could remove this :+1:
