### ISSUE TITLE
Cannot build to .tar file, model.PostActionIntegrationRequesteFromJson not found

### ISSUE THREAD

**Issue by dongtanhuy** [matterpoll/matterpoll#136]
#### Summary
I cannot build the plugin from latest code on `master` branch

#### Steps to reproduce
1. Clone git repository, then Go to `root folder`
2. On terminal: type `make`
3. System running
```
cd server && /usr/local/bin/dep ensure
server/.depensure
Running gofmt
Checking matterpoll/server
Checking matterpoll/server/plugin
Checking matterpoll/server/poll
Checking matterpoll/server/store
Checking matterpoll/server/store/kvstore
Checking matterpoll/server/store/mockstore
Checking matterpoll/server/store/mockstore/mocks
Checking matterpoll/server/utils
Checking matterpoll/server/utils/testutils
Gofmt success
Running govet
```

#### Expected behavior
 I want a .tar file in dist folder to upload to my mattermost server
#### Observed behavior (that appears unintentional)
I cannot find method `PostActionIntegrationRequesteFromJson` in `github.com/mattermost/mattermost-server/model/post.go`
Error message below:
```
# matterpoll/server/vendor/github.com/matterpoll/matterpoll/server/plugin
server/vendor/github.com/matterpoll/matterpoll/server/plugin/api.go:75:13: undefined: model.PostActionIntegrationRequesteFromJson
server/vendor/github.com/matterpoll/matterpoll/server/plugin/api.go:125:13: undefined: model.PostActionIntegrationRequesteFromJson
server/vendor/github.com/matterpoll/matterpoll/server/plugin/api.go:212:13: undefined: model.PostActionIntegrationRequesteFromJson
server/vendor/github.com/matterpoll/matterpoll/server/plugin/api.go:257:42: cannot use response.ToJson() (type []byte) as type string in argument to io.WriteString
# matterpoll/server/poll_test [matterpoll/server/poll.test]
server/poll/poll_test.go:36:67: unknown field 'PublicAddOption' in struct literal of type "matterpoll/server/vendor/github.com/matterpoll/matterpoll/server/poll".PollSettings
server/poll/poll_test.go:70:11: p.AddAnswerOption undefined (type *"matterpoll/server/vendor/github.com/matterpoll/matterpoll/server/poll".Poll has no field or method AddAnswerOption)
server/poll/poll_test.go:77:11: p.AddAnswerOption undefined (type *"matterpoll/server/vendor/github.com/matterpoll/matterpoll/server/poll".Poll has no field or method AddAnswerOption)
server/poll/poll_test.go:83:11: p.AddAnswerOption undefined (type *"matterpoll/server/vendor/github.com/matterpoll/matterpoll/server/poll".Poll has no field or method AddAnswerOption)
server/poll/transform_test.go:195:75: unknown field 'PublicAddOption' in struct literal of type "matterpoll/server/vendor/github.com/matterpoll/matterpoll/server/poll".PollSettings
# matterpoll/server/plugin [matterpoll/server/plugin.test]
server/plugin/api.go:173:16: poll.AddAnswerOption undefined (type *"matterpoll/server/vendor/github.com/matterpoll/matterpoll/server/poll".Poll has no field or method AddAnswerOption)
server/plugin/api.go:219:19: poll.Settings.PublicAddOption undefined (type "matterpoll/server/vendor/github.com/matterpoll/matterpoll/server/poll".PollSettings has no field or method PublicAddOption)
server/plugin/api_test.go:322:17: poll1Out.AddAnswerOption undefined (type *"matterpoll/server/vendor/github.com/matterpoll/matterpoll/server/poll".Poll has no field or method AddAnswerOption)
make: *** [govet] Error 1
```

#### Server configuration
**Operating system:*MacOS mojave 10.14.3*

**Mattermost version:*5.6.0*

**Matterpoll version:*1.0.3*

**Updated from an older Matterpoll version or fresh install:**

#### Additional context
I just pull the code to my local machine and build by using `make` command but I got a error

**Comment by hanzei** [comment]
What go version are you using?

Are you using the latest master or a tag?

Could you please run `rm -rf server/vendor` and then `cd sever && dep ensure`?

**Comment by dongtanhuy** [comment]
Hi, @hanzei  
My go version is: `go version go1.12.1 darwin/amd64`
I cloned the latest master by clicking the green button `Clone or download` on the top right corner to clone code
I run `rm -rf server/vendor` and `cd sever && dep ensure` as you said but it not works,
I just realized that the `PostActionIntegrationRequesteFromJson` existed in version 5.5 of `mattermost-server`

**Comment by hanzei** [comment]
What is the path to the place where you cloned the directory into? Is it in your gopath?

**Comment by dongtanhuy** [comment]
Hi @hanzei 
This is my GOPATH: `GOPATH="/Users/juliandong/Desktop/GoWorkSpace"`
And this is my folder that I cloned `matterpoll` to: `/Users/juliandong/Desktop/GoWorkSpace/src/matterpoll`
It is in my gopath

**Comment by hanzei** [comment]
You need to put it into `/Users/juliandong/Desktop/GoWorkSpace/src/github.com/matterpoll/matterpoll`

**Comment by dongtanhuy** [comment]
Oh yeah, it works. Thank for your instantly support!

**Comment by hanzei** [comment]
You're welcome
