### ISSUE TITLE
Decide which format to use for translations

### ISSUE THREAD

**Issue by hanzei** [matterpoll/matterpoll#139]
Follow up on https://github.com/matterpoll/matterpoll/pull/133#discussion_r262057160

## Possibilities

1. `json`
  - Props: Used by Mattermost translation server
  - Cons: None?
2. `toml`
  - Props: Comments. Default in https://github.com/nicksnyder/go-i18n
  - Cons: None?
3. `yaml`
  - Props: Comments
  - Cons: None?

**Comment by hanzei** [comment]
@kaakaa I would love to hear your thoughts on this, if you have the time.

**Comment by kaakaa** [comment]
I think that `yaml` format is best.
Because for now people who translate messages must edit message files directory, and escaping `"` is troublesome and meaningless works.

**Comment by hanzei** [comment]
I opened an issue for the escaping problem: https://github.com/nicksnyder/go-i18n/issues/160

**Comment by hanzei** [comment]
The issue was been fixed upstream. I updated the description. What do you think now?

**Comment by kaakaa** [comment]
Without any cons, I don't have strong opinions for all formats.
Out of these, `json` would be the best, because it's same as mattermost-server/webapp.

**Comment by hanzei** [comment]
Then let's go with `json` for now. Won't be to hard to change this, if this `json` does become a problem.
