### ISSUE TITLE
missing logo in local network instance

### ISSUE THREAD

**Issue by mindo** [matterpoll/matterpoll#141]
#### Summary
The logo does not appear.
Trying to open the image url I get this error:

```
error fetching remote image: Get https://mattermost.mydomain.com/plugins/com.github.matterpoll.matterpoll/logo_dark.png#0x0: Get https://mattermost.mydomain.com/plugins/com.github.matterpoll.matterpoll/logo_dark.png: address forbidden, you may need to set AllowedUntrustedInternalConnections to allow an integration access to your internal network
```

#### Steps to reproduce
1. Go to any channel
2. Create a poll

#### Expected behavior
The logo should appear next to the poll.

#### Observed behavior

- `mattermost.mydomain.com` resolves to a local network address
- `wget https://mattermost.mydomain.com/plugins/com.github.matterpoll.matterpoll/logo_dark.png` works, so the image is available on the local network

#### Server configuration
**Operating system:**
Ubuntu 14.04

**Mattermost version:**
5.8  - bundled with Gitlab 11.9.1

**Matterpoll version:**
1.0.3

**Updated from an older Matterpoll version or fresh install:**
Updated from 0.1.0

<details>
<summary>Mattermost server logs</summary>

```
{"level":"debug","ts":1553626191.3050966,"caller":"web/handlers.go:50","msg":"GET - /api/v4/image"}
{"level":"error","ts":1553626191.306258,"caller":"log/log.go:289","msg":"error fetching remote image: Get https://mattermost.mydomain.com/plugins/com.github.matterpoll.matterpoll/logo_dark.png#0x0: Get https://mattermost.mydomain.com/plugins/com.github.matterpoll.matterpoll/logo_dark.png: address forbidden, you may need to set AllowedUntrustedInternalConnections to allow an integration access to your internal network","source":"stdlog"}```
</details>

**Comment by riemers** [comment]
Seeing the same issue here. A see a pull request with some items that might be related in the future.

**Comment by mindo** [comment]
Adding this line to `/etc/gitlab/gitlab.rb`:
```
mattermost['service_allowed_untrusted_internal_connections'] = " mattermost.mydomain.com"
```

And the error changed to:
```
forbidden content-type: "text/plain"
```

While trying to debug this I found that the plugin was no longer working but nothing was appearing on the logs.
Disabling the plugin and re-enable it again and everything is working as supposed - the poll works and the log appears.

So at least from our point of view this issue can be closed.

@riemers Can you test this configuration and check if it also sorts it out for you?

**Comment by riemers** [comment]
Adding the current domain of mattermost to the untrusted domains did the trick indeed!

**Comment by mindo** [comment]
:+1:  I am closing the issue.
