### ISSUE TITLE
Possibility for voters to add custom answer

### ISSUE THREAD

**Issue by nado** [matterpoll/matterpoll#142]
#### Summary

When creating an open poll for gathering suggestions, it would be helpful for voters to be able to add a custom answer.

#### Describe alternatives you've considered

We talk and we talk and we make several polls until nobody argues anymore, not efficient...

#### Additional context

Example : 
Where are we going to eat : 

* [ ] sushi
* [ ] burgers
* [ ] Add a new option

**Comment by hanzei** [comment]
Hey @nado,

Thanks for the suggestion. Actually this has been proposed and even implemented before. The feature will be in the next release. See https://github.com/matterpoll/matterpoll/pull/116 for the PR-

**Comment by nado** [comment]
Oh, thanks a lot, I mustnt have used the right keywords to search for existing discussions.
