### ISSUE TITLE
Poll not working - Voting fails - certificate is not valid

### ISSUE THREAD

**Issue by LukasFir** [matterpoll/matterpoll#147]
**Summary**

Voting fails

**Steps to reproduce the behavior:**

    Entering /poll and a question
    Posting poll
    Trying to vote

**Expected behavior:**

Voting result should be counted.

**Following error is displayed:**
-

**Server configuration:**

Operating system: Ubuntu 18.04

Mattermost version: 5.9.0

Matterpoll version: 1.0.3

Matterpoll fresh install

**Log:**
{"level":"error","ts":1555566991.133204,"caller":"web/context.go:52","msg":"Action integration error","path":"/api/v4/posts/8ryhmwxa97dhxepk7mfsx7woay/actions/ird6ekaupb8rt8auudx5t1ibka","request_id":"rmt1t9she3yb8y99aauams5dda","ip_addr":"180.100.190.43","user_id":"rfo6yi55gpfiirxjtx1wg91bro","method":"POST","err_where":"DoActionRequest","http_code":400,"err_details":"err=Post https://intranet.xxx.de/plugins/com.github.matterpoll.matterpoll/api/v1/polls/he7ixdt39i8w98eaq64m58di1o/vote/0: x509: certificate is not valid for any names, but wanted to match intranet.xxx.de"}

**Comment by hanzei** [comment]
Well, this seams to be a problem with your TLS certificates. Are you running Mattermost on a server that doesn't have valid TLS certificate?

**Comment by LukasFir** [comment]
Sorry for the late answer. The certificate is valid and is recognized correctly by websites and Mattermost apps.

**Comment by hanzei** [comment]
> is recognized correctly by websites and Mattermost apps.

This might be the case, but go can handle things differently. Maybe https://github.com/golang/go/issues/24293 is related.

Would you mind sending me your `SiteURL` via a DM on the [Mattermost Community Server](https://community.mattermost.com)?

**Comment by hanzei** [comment]
Closing this one due to inactivity.
