### ISSUE TITLE
Error in log when ending a poll in a DM

### ISSUE THREAD

**Issue by ThiefMaster** [matterpoll/matterpoll#148]
> 2019-04-18T11:46:08.902Z error mlog/sugar.go:23 Failed to post the end poll announcement. {"plugin_id": "com.github.matterpoll.matterpoll", "details": "failed to GetTeam with TeamId: "}

**Comment by hanzei** [comment]
Good catch. Thanks for the report @ThiefMaster

**Comment by hanzei** [comment]
This is hard to fix, because `model.PostActionIntegrationRequest` doesn't contain a `teamId` for DM's.

Opened a discussion in https://community.mattermost.com/core/pl/96pjwmh4o389tbo6c33pnc1xje

**Comment by hanzei** [comment]
This will be fixed ones https://github.com/mattermost/mattermost-server/issues/10688 is fixed.

**Comment by hanzei** [comment]
Requires https://github.com/mattermost/mattermost-webapp/pull/3313 which will be in Mattermost `v5.16`.
