### ISSUE TITLE
Missing translation for slash command

### ISSUE THREAD

**Issue by enetnal** [matterpoll/matterpoll#154]
#### Summary
there is no translationentry for some content

#### Steps to reproduce
just tap `/poll` in the client side and the autoComplete can't be translate

#### Code impact

begin line 156 :
```go
func getCommand(trigger string) *model.Command {
	return &model.Command{
		Trigger:          trigger,
		DisplayName:      "Matterpoll",
		Description:      "Polling feature by https://github.com/matterpoll/matterpoll",
		AutoComplete:     true,
		AutoCompleteDesc: "Create a poll",   <<<< **this one**
		AutoCompleteHint: `"[Question]" "[Answer 1]" "[Answer 2]"...`, <<<< **and this one**
	}
}
```

**Comment by hanzei** [comment]
Hey @enetnal,

Thanks for the report. Sadly, I can't fix on a per-user level. Hence, the server default local could be used for all users. What do you think about this?

See https://mattermost.atlassian.net/browse/MM-14472 for the ticket to fix is on a per-user base.

**Comment by enetnal** [comment]
Hey @hanzei ,
I think the server default loca is a good solution until mattermost add the per-user level.
You already use it for the button translations and it do the trick ^^

thanks

**Comment by enetnal** [comment]
French translation based on the format

"command.autoComplete.desc": {
    "hash": "sha1-1cd8e96070c8a1464138423657b6ffef691fab49",
    "other": "Créer un sondage"
  },
  "command.autoComplete.hint": {
    "hash": "sha1-7355a4eaa6ce5feb9d4b4c0ed10f3af30101bf41",
    "other": "\"[Question]\" \"[Réponse 1]\" \"[Réponse 2]\"..."
  },

**Comment by hanzei** [comment]
Thanks for the help with the translation. But I would much rather translate **all** new string shortly before a release. Please see https://github.com/matterpoll/matterpoll/pull/145#issuecomment-480807477 for the proposed process.
