### ISSUE TITLE
"No such host" when trying to answer poll

### ISSUE THREAD

**Issue by Rhywden** [matterpoll/matterpoll#156]
#### Summary
Whenever someone tries to answer a poll, you get a HTTP 400: No Such Host.

#### Steps to reproduce
1. Fresh install of Mattermost
2. Mattermost still uses Port 8065 as it's still in evaluation and I want to use an Nginx reverse proxy later
3. SITE_URL is thus `http://foo.bar:8065
4. Install Matterpoll plugin
5. Create vote
6. Try to vote

#### Expected behavior
The vote should be registered

#### Observed behavior (that appears unintentional)
The vote is not registered. The logs show this error message:

```
{"level":"error","ts":1558023207.4892235,"caller":"mlog/log.go:172","msg":"Action integration error","path":"/api/v4/posts/efbuoo4kiffc7m8uospbxbu31e/actions/dq5m9pg9qbywpns94tn413mcjc","request_id":"7ragauffz7de9noipiueexmody","ip_addr":"my.public.ip.address","user_id":"snx1ozb6sjr47yatd3abjrpgbo","method":"POST","err_where":"DoActionRequest","http_code":400,"err_details":"err=Post http://http//foo.bar:8065//plugins/com.github.matterpoll.matterpoll/api/v1/polls/tkgm41ndmfywxxnn7su85hfgho/vote/0: lookup http on some.random.ip.address:53: no such host"}
```

Please note that I have no idea where `some.random.ip.address:53` is coming from. It certainly isn't my server, nor is it my client. The doubled `http` part before my server's URI is also weird.

#### Server configuration
**Operating system:**
Ubuntu 18.04

**Mattermost version:**
5.10.0

**Matterpoll version:**
1.1.0

**Updated from an older Matterpoll version or fresh install:**
Fresh install

<details>
<summary>Mattermost server logs</summary>

```
{"level":"error","ts":1558023207.4892235,"caller":"mlog/log.go:172","msg":"Action integration error","path":"/api/v4/posts/efbuoo4kiffc7m8uospbxbu31e/actions/dq5m9pg9qbywpns94tn413mcjc","request_id":"7ragauffz7de9noipiueexmody","ip_addr":"my.public.ip.address","user_id":"snx1ozb6sjr47yatd3abjrpgbo","method":"POST","err_where":"DoActionRequest","http_code":400,"err_details":"err=Post http://http//foo.bar:8065//plugins/com.github.matterpoll.matterpoll/api/v1/polls/tkgm41ndmfywxxnn7su85hfgho/vote/0: lookup http on some.random.ip.address:53: no such host"}
```
</details>

**Comment by hanzei** [comment]
Did you set your site URL correctly? It should start with `https://`.

**Comment by Rhywden** [comment]
It's currently still on `http` because we're in the internal testing phase.

**Comment by hanzei** [comment]
But still, the site URL seams to be wrongly set. e.g. it should not end with a `/`.

**Comment by Rhywden** [comment]
Which it does not in my settings.

![image](https://user-images.githubusercontent.com/84586/57881943-d2101000-7822-11e9-9466-46ad40489fbf.png)

**Comment by hanzei** [comment]
Would you please find out where the information `some.random.ip.address:53` is coming from? I strongly suppose this is part of the issue.

**Comment by Rhywden** [comment]
Upon further research, this seems to be a DNS server from my hosting provider. So not the culprit.

**Comment by Rhywden** [comment]
Okay, found it. I did indeed have a misconfigured SITE_URL for a bit (as you said, trailing slash). However, I corrected that before coming here.

What I did do, however, was to still try an *existing* poll. I just deleted the poll and created a new one - it's working now. It seems that changes to the SITE_URL setting don't get picked up in existing polls.

**Comment by hanzei** [comment]
> It seems that changes to the SITE_URL setting don't get picked up in existing polls.

That is correct. But due to restrictions from the Mattermost this isn't fixable in Matterpoll.
