### ISSUE TITLE
Translations and the hint help for the poll

### ISSUE THREAD

**Issue by jsalatiel** [matterpoll/matterpoll#159]
Hi, I am trying to create a translation for Brazilian Portuguese, so I have taken the english i18n file and translated to Brazilian Portuguese. I have also changed the "/pool" command to "/enquete". The problem that i am facing is that when the user starts typing "/enquete" the help hint will still be shown in english and i can not find the string reference for that in the i18n files.
![image](https://user-images.githubusercontent.com/5522389/58610193-fa672800-8280-11e9-8944-b0d53dddcd17.png)

What am i missing ?

**Comment by hanzei** [comment]
The current release Matterpoll `v1.1.0` doesn't support translating the slash command help text. This will already fixed on `master' and will be part of the next release. See https://github.com/matterpoll/matterpoll/pull/155 for the PR that fixed this.

Other question: Would you be interested in helping with the Portuguese translation?

**Comment by jsalatiel** [comment]
Great news!
Sure i can help. What should i do ?

**Comment by hanzei** [comment]
Hey @jsalatiel,

I outlined some documentation on how to translate Matterpoll in #166. Would you be open on trying it out and sharing your feedback on this documentation?

**Comment by hanzei** [comment]
Closing this for now, as the original issue has ben solved.
