### ISSUE TITLE
Received invalid response from the server. when installing plugin

### ISSUE THREAD

**Issue by msg-sattlerf** [matterpoll/matterpoll#171]
#### Summary
I downloaded the actual matterpol tar.gz. and wanted to upload it to my mattermost.
After a while the error "Received invalid Response from the Server" showed up

#### Steps to reproduce
1. Go to Plugins (BETA) -> Management -> Choose File -> Choose the actual tar.gz
2. Click on upload
3. See error

#### Expected behavior
The plugin should be installed without an error

#### Server configuration
Debian GNU/Linux 9 (Stretch)

Mattermost version: 5.8.0

Matterpoll version: 1.1.0

Updated from an older Matterpoll version or fresh install: tried to fresh install

**Comment by hanzei** [comment]
Hey @msg-sattlerf,

Thanks for the report. Would you please
1. Update your Mattermost Server to the latest version
2. Try uploading a different plugin like https://github.com/mattermost/mattermost-plugin-github and see if this works
?

**Comment by mihai-satmarean** [comment]
Same here, Latest mattermost Mattermost Version: 5.11.0
Database Schema Version: 5.11.0
Database: postgres and tying to upload com.github.matterpoll.matterpoll-1.1.0.tar.gz, gives this error:
 Unable to install plugin. A plugin with the same ID is already installed and failed to be removed.

**Comment by mihai-satmarean** [comment]
thanks! maybe I am just confused but for me is:
Matterpoll v1.1.0 supports Mattermost v5.10.0 or higher.
we have Mattermost Version: 5.11.0 which is higher  than 5.10.0

**Comment by kaakaa** [comment]
@mihai-satmarean 
Yes, maybe you're right. I supposed that your case is differ from @msg-sattlerf's case, and I commented on just @msg-sattlerf's case. Or are you on the same instance?

**Comment by mihai-satmarean** [comment]
yes, I missed the details, thought is the same ... I have no way to upload the new version and the plugin manager does not want to remove the old one, so we are stuck

**Comment by kaakaa** [comment]
Okay. I think that the message you pasted above is often output when there is a problem with the environment.

So may I check the following?
1. Can you upload a different plugin like https://github.com/mattermost/mattermost-plugin-github and 
see if this works?
2. Can you remove existing matterpoll plugin

**Comment by mihai-satmarean** [comment]
Actually, we just installed the https://github.com/mattermost/mattermost-plugin-github.
cannot remove the existing matterpoll plugin. any manual way?
Thanks!

**Comment by kaakaa** [comment]
Thank you for confirming. @mihai-satmarean 
I meant "removing matterpoll from admin console", sorry for my ambiguous comment. Removing a plugin in manual way is not recommended as it may cause inconsistencies.

Hmm...but, it's curious. Your plugin environment might be correct...
Would you open this in [Mattermost forum](https://forum.mattermost.org/)? Your issue seems to be related to Mattermost platform, not just to Mattempoll plugin. In the forum, I think that you can get more useful opinions about mattermost platform.

**Comment by hanzei** [comment]
@mihai-satmarean Are you still encountering this problem?

**Comment by mihai-satmarean** [comment]
yes.  could not move from there

În mie., 7 aug. 2019 la 15:22, Hanzei <notifications@github.com> a scris:

**Comment by hanzei** [comment]
Can you elaborate why you can't remove the previous version of Matterpoll? And could you also update your Mattermost server to 5.12?

**Comment by hanzei** [comment]
Closing this one due to inactivity. @mihai-satmarean @msg-sattlerf Please reopen, if the issue does come up again.

**Comment by heidricha** [comment]
same issue with mattermost 5.33 and matterpoll 1.2 - 1.4
server is a gitlab omnibus container. matterpoll used to work on the same server. I cannot recall the last working version, but we sometimes use the plugin, so I guess it couldn't be more then a few months before when we was last able to use it.
