### ISSUE TITLE
Allow creating of poll via interactive dialog

### ISSUE THREAD

**Issue by hanzei** [matterpoll/matterpoll#199]
#### Summary

Creating a poll via the slash command can be hard and error prone. As an easier option we should allow the creation via an interactive dialog. Users should be able provided answer options and select poll settings. The dialog opens when a users enters `/poll`.

#### Describe alternatives you've considered

How many options should they be able to enter? 3? 5?

#### Additional context

Requires https://github.com/mattermost/mattermost-webapp/pull/3066, which will ship with MM `5.16`

**Comment by colorfusion** [comment]
This is a pretty neat feature since it makes the poll creation much more intuitive. Mattermost has already released `5.16` a while back, will you be looking into merging #220 in anytime soon?

**Comment by hanzei** [comment]
@colorfusion I pushed an update to #220 and hope to merge it soon. Stay tuned!
