### ISSUE TITLE
Add CSS for "Add Option", "Delete Poll", and "End Poll" Buttons

### ISSUE THREAD

**Issue by jfrerich** [matterpoll/matterpoll#211]
#### Summary

This feature request is to add some CSS to differentiate poll "controlling" buttons from the vote option buttons.

#### Describe alternatives you've considered

N/A 

#### Additional context

![image](https://user-images.githubusercontent.com/7575921/63643495-1d924f80-c697-11e9-9164-7ab08511e255.png)

**Comment by hanzei** [comment]
Thanks for sharing your idea @jfrerich. Would the approach in #121 fix your issue?

**Comment by jfrerich** [comment]
@hanzei, sure that would work and it was just an I observation.  I was looking at matterpoll and it's capabilities as a possible way to collect / rank different tools in the Dev Tool Discussions channel.

**Comment by hanzei** [comment]
@jfrerich Would you be fine, if I close this issue on favour of #121?

If you have other feedback, feel free to reach out to me or open a new issue.

**Comment by jfrerich** [comment]
Closing. Thanks, @hanzei.
