### ISSUE TITLE
"Add option" button is usable even without the --public-add-option

### ISSUE THREAD

**Issue by SnorreSelmer** [matterpoll/matterpoll#227]
I've made a couple of polls for testing, and despite not having added the --public-add-option flag, I (and others) could add options. It might be a SysAdmin-thing, but unless you specify that you want more options, nobody should be able to add options (maybe except the creator)?

**Comment by hanzei** [comment]
The current behaviour should be that the creator and system admins can add options. Can you confirm this?

**Comment by SnorreSelmer** [comment]
I'll test it when I get back to the office tomorrow. If I understand
correctly, what you're saying is, the buttons show up no matter what, but
aren't usable unless people have the right permissions?
Before rolling this out, we've been testing it within a group, and we're
all sysadmins, so I guess we've made the perfect anti-test-environment.
Thanks for helping. :)

**Comment by hanzei** [comment]
>  If I understand
correctly, what you're saying is, the buttons show up no matter what, but
aren't usable unless people have the right permissions?

That is correct. See https://github.com/matterpoll/matterpoll/issues/73 for more context.

**Comment by SnorreSelmer** [comment]
OK, my bad. I tested it with another user that isn't SysAdmin, and he
confirmed that while he saw the buttons, he wasn't allowed to interact with
them.

**Comment by hanzei** [comment]
Thanks for confirming :+1:

Closing
