### ISSUE TITLE
Revise helper text to remove brackets

### ISSUE THREAD

**Issue by sei-dmorda** [matterpoll/matterpoll#230]
#### Summary
The slash command's helper text can confuse users who aren't familiar with the technical syntax of brackets. It's more of a usability issue than a bug.

#### Steps to reproduce
1. Open Mattermost
2. Enter a poll as shown in the helper text (e.g,. /poll "[Who will win the Super Bowl?]" "[Steelers]" "[Browns]" "[Ravens]"
3. Review results

#### Expected behavior
A poll that says...

**Poll Question:**
Who will win the Super Bowl?

**Poll Choices:**
- Steelers
- Browns
- Ravens

#### Observed behavior (that appears unintentional)
A poll that says...

**Poll Question:**
[Who will win the Super Bowl?]

**Poll Choices:**
- [Steelers]
- [Browns]
- [Ravens]

#### Server configuration
**Operating system:**
RHEL 7

**Mattermost version:**
5.15

**Matterpoll version:**
1.2.0

**Comment by hanzei** [comment]
Hey @sei-dmorda,

Thanks for sharing your idea. I'm wondering why someone would use both `"` and `[` around there options? Is it because of the suggestion text?

**Comment by sei-dmorda** [comment]
You guessed it, it was because of how the suggestion text was worded. I think if the suggestion text was the below, it would be more clear.

/poll "Question" "Answer 1" "Answer 2"...

**Comment by hanzei** [comment]
With https://github.com/matterpoll/matterpoll/pull/220 in place, people will use `/poll` more as it's more user friendly. I'm not convinced that changing the help text will result in less confusion.
