### ISSUE TITLE
GolangCI always fails

### ISSUE THREAD

**Issue by kaakaa** [matterpoll/matterpoll#236]
#### Summary
Bug report in one concise sentence

#### Steps to reproduce
1. Create PR

#### Expected behavior
* golang-ci run successfully

#### Observed behavior (that appears unintentional)
* `analyze` phase of GolangCI always fails
https://golangci.com/r/github.com/matterpoll/matterpoll/pulls/232

```
analyze (0.7s)
$ GOLANGCI_COM_RUN=1 golangci-lint run --out-format=json --issues-exit-code=0 --deadline=5m --new=false --new-from-rev= --new-from-patch=../changes.patch ./...
    Running error: context loading failed: failed to load program with go/packages: could not determine GOARCH and Go compiler
```

#### Server configuration
N/A

#### Additional context
Related?
https://github.com/golang/go/issues/30355

**Comment by hanzei** [comment]
Maybe https://github.com/golangci/golangci-lint/issues/440 is related
