### ISSUE TITLE
Requests to API can be spoofed if Experimental UI is enabled

### ISSUE THREAD

**Issue by hanzei** [matterpoll/matterpoll#245]
If Experimental UI is enabled, we send a websocket event containing among other things the `pollID`. Any user receiving this websocket event can then use the `pollID` to handcraft events to the API and trigger events. E.g. he/she can vote a other users.

The easy solution is to include a `token` in `context` and check it on reviving. But this would be a breaking change.

I will be hard to fix this without introducing a breaking change. This can partly be fixed by checking if `Mattermost-User-ID` is the same as the `userID` in the request. With this change the user can only forge requests as himself. This still allows voting for channels the user is not part of any longer.

**Comment by hanzei** [comment]
Checks like https://github.com/matterpoll/matterpoll/pull/246/files#diff-4444f0caa92e553b5c018c908e90e5e6R153-R156 won't help, as 'request.ChannelId` as also be spoofed.

**Comment by hanzei** [comment]
@kaakaa Let me know what you think

**Comment by kaakaa** [comment]
@hanzei 
Specifications about exposing pollId has been discussed in [this issue](https://github.com/matterpoll/matterpoll/issues/28#issuecomment-443407832). 

As far as I know, users who get poll_id can't impersonate others, because any requests will be checked if the request is created by authenticated user by [checkAuthenticity function](https://github.com/matterpoll/matterpoll/blob/master/server/plugin/api.go#L128). 
And [this thread](https://community.mattermost.com/core/pl/jasa6eioabytufgsqn1i545bza) for discussing about `Mattermost-User-Id` header is related to this issue.

 
So I think that anyone can't spoof requests for polling.

**Comment by hanzei** [comment]
The value of `Mattermost-User-Id` is the userID that issued the http request. But a authenticated user (e.g. one with a valid session) can create a http request to vode as another user by just using a valid session.

**Comment by kaakaa** [comment]
> But an authenticated user (e.g. one with a valid session) can create a http request to vode as another user by just using a valid session.

Really? I supposed that `Mattermost-User-Id` can be set only by mattermost-server. Even if client set `Mattermost-User-Id` as request header, it will drop by mattermost-server and mattermost-server set correct user id.

---

* Mattermost has two users (USER_ID_1, USER_ID_2)
* USER_ID_1 generate access token (ACCESS_TOKEN_USER1)
* Send two requests with different `Mattermost-User-Id` value
```
curl -H "Mattermost-User-Id: ${USER_ID_1}" -H "Authorization: Bearer ${ACCESS_TOKEN_USER1}" http://localhost:8065/plugins/com.github.matterpoll.matterpoll/api/v1/configuration
```
```
curl -H "Mattermost-User-Id: ${USER_ID_2}" -H "Authorization: Bearer ${ACCESS_TOKEN_USER1}" http://localhost:8065/plugins/com.github.matterpoll.matterpoll/api/v1/configuration
```

* Read `Mattermost-User-Id` in plugin api https://github.com/matterpoll/matterpoll/blob/master/server/plugin/api.go#L130

For these two requests, I confirmed that `r.Header.Get("Mattermost-User-ID")` returns `USER_ID_1`, not `USER_ID_2`.

---

If you know an example that can be spoofed, please let me know it.
