### ISSUE TITLE
Default settings for all Pulls (--progresbar --anonymous and etc.)

### ISSUE THREAD

**Issue by hangmana** [matterpoll/matterpoll#248]
#### Summary
In our company we want to see number of votes for each button, but it (--progress) hard to type for each time.

if it is in the settings it would be cool.
but then we will want you to add (--noprogress) option for disable it in some votes

#### Additional context
![default settings](https://user-images.githubusercontent.com/35597729/69439175-76858880-0d57-11ea-8d9d-4304d40eb6da.JPG)

**Comment by akomakom** [comment]
Failing that, I'd be happy with these hard-to-remember options being mentioned in the auto-completion help popup.

**Comment by hanzei** [comment]
With https://github.com/matterpoll/matterpoll/pull/220 in place, this makes much sense. My proposal would be to only apply the setting to the dialog and not polls created via CLI.
