### ISSUE TITLE
matterpoll_bundle.js: no such file or directory

### ISSUE THREAD

**Issue by PlutarcoII** [matterpoll/matterpoll#258]
#### Summary
matterpoll_bundle.js: no such file or directory

#### Steps to reproduce
1. I downloaded and  installed matterpoll plugin with no error
2. Then, I activated matterpoll plugin and I got matterpoll_bundle.js: no such file or directory in LOGS

#### Observed behavior (that appears unintentional)
What did you see happen? Please include relevant error messages and/or screenshots.

#### Server configuration
Ubuntu amd64

**Mattermost version:**
4.6.0 Base de Datos postgres

**Matterpoll version:**
1.30

**Updated from an older Matterpoll version or fresh install:**
Fresh Install 

<details>
<summary>Mattermost server logs</summary>
com.github.matterpoll.matterpoll_bundle.js: no such file or directory

```
[2020/02/21 11:10:47 CST] [EROR] unable to read webapp bundle: com.github.matterpoll.matterpoll: open ./plugins/com.github.matterpoll.matterpoll/webapp/com.github.matterpoll.matterpoll_bundle.js: no such file or directory

```

</details>

**Comment by hanzei** [comment]
Hi @PlutarcoII,

Thanks for your report. What Mattermost version are you using?

**Comment by PlutarcoII** [comment]
Hi @hanzei 

My Mattermost versión is 4.6.0

thanks

**Comment by hanzei** [comment]
@PlutarcoII Would you please update to at least Mattermost version 5.14 and try again?

**Comment by PlutarcoII** [comment]
Hi @hanzei 

We have scheduled an update for mattermost next weekend. 
Next Monday, I'll send you an update of this issue.

Thanks for your answer and advice.

**Comment by PlutarcoII** [comment]
Hi @hanzei 

Yesterday, We have installed Mattermost version 5.14. 
Now, Matterpoll is working as expected. 

Thanks you.

![image](https://user-images.githubusercontent.com/15706449/76872861-9b37cb80-6832-11ea-9b52-f3e3ef7bdfeb.png)
