### ISSUE TITLE
Move i18n code into own package

### ISSUE THREAD

**Issue by hanzei** [matterpoll/matterpoll#260]
This helps to isolate the code more and get allows us to drop `localizer.MustLocalize`, which caused https://github.com/matterpoll/matterpoll/issues/252

**Comment by hanzei** [comment]
@kaakaa I spend some time thinking about this and would like to hear your thoughts:

#### Goals
1. Encapsulate the functionality into a sigle package
2. Have a clear interface towards the package consumer
3. Avoid forcing consumers to import `github.com/nicksnyder/go-i18n/v2/i18n`


The main issue I hit was that most messages of the new `i18n` package expect a `*i18n.Message` or `*i18n.Localizer`. Given that the goal is to avoid an import of `github.com/nicksnyder/go-i18n/v2/i18n` I did nest e.g. `github.com/nicksnyder/go-i18n/v2/i18n.Message` into `i18n.Message`. This causes the problem that the consumer can't use composite literals to create structs.
> Promoted fields act like ordinary fields of a struct except that they cannot be used as field names in composite literals of the struct.

https://golang.org/ref/spec#Struct_types

I'm unsure how to continue. Is goal 3 not achievable with go?

**Comment by kaakaa** [comment]
@hanzei  Sorry for my late.

[Type alias](https://golang.org/ref/spec#Type_declarations) can hide `github.com/nicksnyder/go-i18n/v2/i18n.Message` from consumer. (but, it may looks hacky.)

```
package i18n

import "github.com/nicksnyder/go-i18n/v2/i18n"

// consumer can refer WrappedMessage type as original i18n.Message type
type WrappedMessage i18n.Message
```

**Comment by hanzei** [comment]
https://pkg.go.dev/github.com/mattermost/mattermost-plugin-api@v0.0.12/i18n should be used

**Comment by kaakaa** [comment]
I switched back to use `github.com/nicksnyder/go-i18n/v2/i18n` by #419, because `goi18n extract` collects messages declared only by `github.com/nicksnyder/go-i18n/v2/i18n.Message`, not aliased type.
