### ISSUE TITLE
Customize button color

### ISSUE THREAD

**Issue by kaakaa** [matterpoll/matterpoll#267]
#### Summary
Changing buttons colors depending on their role (Answer, Add Options, Delete/End...) improves visibility. 

Example:
* Answer Option - blue
* Add Option - grey
* Delete/End - red

#### Additional context
webapp: [\[MM\-22734\] Support different interactive message button styles by kosgrz · Pull Request \#4993 · mattermost/mattermost\-webapp](https://github.com/mattermost/mattermost-webapp/pull/4993)
mobile: [MM\-10160 \- support interactive button styles by RyanCommits · Pull Request \#3896 · mattermost/mattermost\-mobile](https://github.com/mattermost/mattermost-mobile/pull/3896)

**Comment by hanzei** [comment]
@kaakaa Are you suggestion using custom hex colors?

I would go with:
- Answer Option - `default`
- Add Option - `primary`
- End - `primary`
- Delete - `danger`

to keep the poll "not to shiny"

**Comment by kaakaa** [comment]
> Are you suggestion using custom hex colors?

No. My suggestion is just an idea.

Your suggestion is almost fine for me, but I think that it's better to use the same color  for End/Delete button, because the both of End and Delete button require admin permission.

* Answer Option - default
* Add Option - primary
* Delete - danger
* End - danger

how sounds?

**Comment by hanzei** [comment]
Let's try out both versions and make a decision then

**Comment by kaakaa** [comment]
I tried some styles. `Option1` looks good for me, because I feel like the primary colored option button looks the most like the default. @hanzei what do you think?

### (Notes)
We can use these styles for buttons (Hex is arbitrary color, but I don't want to use it)
![スクリーンショット 2020-06-21 13 17 38](https://user-images.githubusercontent.com/1453749/85217073-ab2df100-b3c7-11ea-8060-c76a0eb388db.png)

### Option1 ([issue body](https://github.com/matterpoll/matterpoll/issues/267#issue-576579454))

(Changed the color of End to `green`)

* Answer: `primary`
* AddOption: `default`
* Delete: `danger`
* End: `good`

![スクリーンショット 2020-06-21 13 20 55](https://user-images.githubusercontent.com/1453749/85217059-8c2f5f00-b3c7-11ea-8e8b-b78cc52010bb.png)



### Option2 ([hanzei's comment](https://github.com/matterpoll/matterpoll/issues/267#issuecomment-595614190))
* Answer: `default`
* AddOption: `primary`
* Delete: `danger`
* End: `primary`

![スクリーンショット 2020-06-21 13 16 18](https://user-images.githubusercontent.com/1453749/85217055-7b7ee900-b3c7-11ea-96fd-ccb1e9b4cfda.png)

### Option3 ([kaakaa's comment](https://github.com/matterpoll/matterpoll/issues/267#issuecomment-596530915))

* Answer: `default`
* AddOption: `primary`
* Delete: `danger`
* End: `danger`

![スクリーンショット 2020-06-21 13 18 19](https://user-images.githubusercontent.com/1453749/85217058-85a0e780-b3c7-11ea-9368-8c254935ed17.png)

* * *

### Option1 with ExperimentalUI setting
![スクリーンショット 2020-06-21 13 52 49](https://user-images.githubusercontent.com/1453749/85217063-97828a80-b3c7-11ea-9580-1e85d30332f8.png)

### Option2 with ExperimentalUI setting
![スクリーンショット 2020-06-21 13 59 04](https://user-images.githubusercontent.com/1453749/85217065-9b161180-b3c7-11ea-8c53-5e72d6f6548f.png)

**Comment by hanzei** [comment]
The red `End Poll` in Option3 seem to strong to me. Ending a poll is a normal task and the user shouln't be scared. 

I quite like Option2. There are just a few distinct colors. Green for `End Poll` seams like a confirmation button, which is isn't.

OT: Maybe we swap the positioning of `Delete Poll` and `End Poll`. What would group the two blue buttons.

**Comment by hanzei** [comment]
@asaadmahmood I would love to hear you thoughts on this, if you have the time.

**Comment by asaadmahmood** [comment]
@hanzei If we do not treat this as an example. I like the idea, though I'd strongly suggest making this theme compatible and using theme colors (we should be able to achieve most of what we have here with theme colors).

For destructive actions, I like the red, and I think delete poll red is fine, as it is destructive.  End poll blue looks fine to me.
For the yes and no functionality. wondering if we should just follow the emoji reaction pattern, where it is grayed out if you have not selected it, and blue outlined when you have.

**Comment by kaakaa** [comment]
Thanks for comment @hanzei , @asaadmahmood, and I'm sorry for my late reply. I re-implemented button colors with **Option 2** and theme compatibility, and create WIP PR #374. 

@hanzei @asaadmahmood 
What do you think of the following styles?

## Normal
<img width="674" alt="スクリーンショット 2021-03-01 21 40 26" src="https://user-images.githubusercontent.com/1453749/109499182-e399d900-7ad7-11eb-83ac-83c38fbc747b.png">

## Experimental UI (Theme: Mattermost)

<img width="676" alt="スクリーンショット 2021-03-01 21 40 04" src="https://user-images.githubusercontent.com/1453749/109499322-147a0e00-7ad8-11eb-8591-b8f104ab974a.png">

## Experimental UI (Theme: Organization)

<img width="676" alt="スクリーンショット 2021-03-01 21 40 04" src="https://user-images.githubusercontent.com/1453749/109499345-1e9c0c80-7ad8-11eb-8ae3-d0663fcc74fe.png">

## Experimental UI (Theme: Mattermost Dark)

<img width="679" alt="スクリーンショット 2021-03-01 21 39 32" src="https://user-images.githubusercontent.com/1453749/109499359-2491ed80-7ad8-11eb-9de3-873c6db3315a.png">

## Experimental UI (Theme: Windows Dark)

<img width="679" alt="スクリーンショット 2021-03-01 21 39 15" src="https://user-images.githubusercontent.com/1453749/109499376-28be0b00-7ad8-11eb-80de-e3fc81a09ddf.png">

---

Just one thing, following the emoji reaction pattern seems to be confusion, so I used inverted color pattern for yes / no functionality.

<img width="780" alt="スクリーンショット 2021-02-28 22 45 36" src="https://user-images.githubusercontent.com/1453749/109499688-92d6b000-7ad8-11eb-9455-ce65dc757e18.png">
