### ISSUE TITLE
Display how many people have voted

### ISSUE THREAD

**Issue by kaakaa** [matterpoll/matterpoll#27]
We cannot know how many people have voted until poll is ended.
It had better to display the number of votes on poll post

Sample: 
![2018-08-24 13 22 52](https://user-images.githubusercontent.com/1453749/44565041-0b8a8200-a7a1-11e8-96ad-95b3185069e4.png)

**Comment by Hanzei** [comment]
Would you show how many people have voted in general or how many people voted for every option?

**Comment by kaakaa** [comment]
I'm saying the former. I want to know how many people voted in general.
It's no problem that the number of votes for every options is showed only after pushing EndPoll.
