### ISSUE TITLE
GolangCI.com will be closing in April 15

### ISSUE THREAD

**Issue by kaakaa** [matterpoll/matterpoll#271]
#### Summary

[GolangCI\.com is closing \- golangci \- Medium](https://medium.com/golangci/golangci-com-is-closing-d1fc1bd30e0e)

We should run `golangci-lint` in other services (e.g.: CircleCI, GitHub Actions, and so on).

If new version of [orb/mattermost/plugin-ci](https://circleci.com/orbs/registry/orb/mattermost/plugin-ci) is released, it seems to help us to run `golangci-lint` in CircleCI. Should we wait for the new version of plugin-ci orb? or investigate how to run `golangci-lint` in GitHub Actions (FYI. https://github.com/reviewdog/action-golangci-lint) ?

**Comment by hanzei** [comment]
I'm currently working on setting a new version of https://circleci.com/orbs/registry/orb/mattermost/plugin-ci released soon. Hence, we should be able to just use it, when it's released.

**Comment by hanzei** [comment]
@kaakaa Heads up that I disabled the GitHub check from https://golangci.com. We only rely on CircleCI now.
