### ISSUE TITLE
Improve UX after clicking an option to vote

### ISSUE THREAD

**Issue by esethna** [matterpoll/matterpoll#277]
#### Summary

Clicking a button to vote when the poll is scrolled up higher in the channel history does not provide feedback to the user, since the ephemeral system post confirming your vote appears off screen.

#### Ideas

Perhaps we could update the UI of the poll post itself to make it obvious that users have voted and what they voted for without relying on the system message

**Comment by hanzei** [comment]
Hey @esethna,

Thanks for providing feedback. Did you tried out the "Experimental UI", which can be enabled in the System console? With it activated, users can see what option they voted for. Please note that this doesn't work on mobile due to the limitations of the plugin toolkit.

**Comment by esethna** [comment]
Ah thanks, no I haven't tried that
