### ISSUE TITLE
Matterpoll HTTP 404 error for older poll

### ISSUE THREAD

**Issue by oli-ver** [matterpoll/matterpoll#278]
#### Summary
A poll that has been active for some days is not available anymore: It's visible in Mattermost, but clicking on its options does not result in any action on the frontend. New polls do work without any issues.

#### Steps to reproduce
Steps to reproduce the behavior (not sure if reproducable):
1. Create a poll
2. Let it active for some days
3. Try to vote for something
4. See error "Invalid Action ID"

#### Expected behavior
Poll remains active until actively ended by the creator

#### Observed behavior (that appears unintentional)
What did you see happen? Please include relevant error messages and/or screenshots.

Clicking on options results in the following errors in the web call (Chrome web console):

```
{"id":"api.post.do_action.action_id.app_error","message":"Ungültige Action-ID","detailed_error":"","request_id":"mffzagknmbb3d8ofsx9dio41pr","status_code":404}
```

"Ungültige Action-ID" means "Invalid Action ID"

On the backend side I can see the following log message quite often:

```
web_1  | 192.168.203.1 - - [24/Mar/2020:12:06:43 +0100] "POST /api/v4/posts/fd4qs58ihjgateqje1iejj9i4y/actions/owzbqdqfgfn53djxhp6yg4q74h HTTP/1.1" 404 160 "-" "Mozilla/5.0 (Linux; Android 9; FP3 Build/8901.2.A.0110.20200109; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/80.0.3987.149 Mobile Safari/537.36" "<someip>"
```

#### Server configuration
**Operating system:**
Distributor ID:	Debian
Description:	Debian GNU/Linux 9.11 (stretch)
Release:	9.11
Codename:	stretch

**Mattermost version:**
5.12.1

**Matterpoll version:**
1.2.0
**Updated from an older Matterpoll version or fresh install:**

Fresh Install
<summary>Mattermost server logs</summary>

```
Already provided earlier
```
</details>

#### Additional context
-

**Comment by hanzei** [comment]
@oli-ver Would you please update your Mattermost version? It hard to debug the issue on an one year old server version. Would you also please update your Matterpoll version?

**Comment by oli-ver** [comment]
Thank you for the response @hanzei. I will do that on Monday and create a poll that I will leave open for some days to test with.

**Comment by hanzei** [comment]
@oli-ver Did you got the time to update your Mattermost Server?

**Comment by oli-ver** [comment]
Hello @hanzei,

yes, I updated mm and the addon. I did not see the issue reoccurring. In my opinion the issue can be closed.
