### ISSUE TITLE
Is it me, or does the ReadMe lack build instructions?

### ISSUE THREAD

**Issue by seanm** [matterpoll/matterpoll#286]
I realize there are pre-built binaries available, but I'd prefer to build myself if at all possible. I downloaded the source tarball, but the ReadMe doesn't seem to have any build instructions.  Am I just missing them?

Thanks.

**Comment by hanzei** [comment]
@seanm That is 100% correct :wink: Are you interested in adding build instructions to `CONTRIBUTING.md`?

**Comment by seanm** [comment]
Uuuhh, if I knew *how*, I wouldn't need instructions. :)
