### ISSUE TITLE
Hide inactive buttons

### ISSUE THREAD

**Issue by globalqss** [matterpoll/matterpoll#291]
When a new poll is created it shows the three buttons (Add option, Delete poll, End poll) to everybody.

![buttonspoll](https://user-images.githubusercontent.com/744634/80310051-f2896e00-87d8-11ea-88c9-74a5ef71f52e.png)

When normal users try to use them, the message is shown:
* Only the creator of a poll and System Admins are allowed to add options.  (UNLESS you have created the poll with --public-add-option)
* Only the creator of a poll and System Admins are allowed to delete it.
* Only the creator of a poll and System Admins are allowed to end it.

From UX perspective the buttons that cannot be used must be hidden - or at least clearly inactive (dimmed and not clickable).

**Comment by kaakaa** [comment]
commented on https://github.com/matterpoll/matterpoll/issues/289#issuecomment-621590705.

**Comment by hanzei** [comment]
Closing as duplicate https://github.com/matterpoll/matterpoll/issues/291
