### ISSUE TITLE
Single setting button

### ISSUE THREAD

**Issue by privat** [matterpoll/matterpoll#295]
Replace the 3 edition buttons (add, delete, close) with a single one that open a settings window with various actions.

The current issues of the 3 buttons are:

* They take a large amount of space. Especially in some locale where the translations of the button labels are quite verbose
* They confuse new users
* They limit settings to 3 actions. eg. no way to update description or toggle options

I also suggest labeling the new single button with a cog/gear ⚙️ symbol or something equally 
concise commonly used for setting buttons.

Note : the setting button should not be restricted to editors and should also be used by users. eg to add option if allowed. If possible, only the actions permitted to the user should be shown in the setting window.

**Comment by hanzei** [comment]
With https://github.com/matterpoll/matterpoll/pull/234 merged, the buttons will not longer be shown to all users.

Also the integration framework that Mattermost provides only allows a sigle button for modals. Hence, it's currently not possible to implement the proposal. I'm also hesitant to increase the number of clicks a user has to do to end or delete a poll.

**Comment by hanzei** [comment]
https://github.com/matterpoll/matterpoll/pull/234 improves the UX quite a bit. I'm not convinced a single button helps much more. Closing.
