### ISSUE TITLE
Emojis in poll results

### ISSUE THREAD

**Issue by raihle** [matterpoll/matterpoll#309]
#### Summary

Emoji (e.g. `:star:`) should be parsed and displayed (as ":star:") in the poll result messages.

#### Describe alternatives you've considered

Not using emoji. But that's boring!

#### Additional context

Now that #127 is resolved and emoji are parsed for the option buttons, it is jarring to see them in text form when the results are presented. 

![matterpoll-emoji-issue](https://user-images.githubusercontent.com/985768/87678345-1d9db100-c77b-11ea-8c38-566a607b61ac.png)

**Comment by kaakaa** [comment]
Thanks @raihle .
That happens only when enabling `ExperimentalUI`. I've created PR to fix this.
