### ISSUE TITLE
Trying to enable plugin failes

### ISSUE THREAD

**Issue by erezo9** [matterpoll/matterpoll#314]
#### Summary
Bug report in one concise sentence
under k8s helm chart installation, tried to install the plugin

#### Expected behavior
the plugin will start normalyy

#### Observed behavior (that appears unintentional)
error starting plugin - log message
`2020-08-04T08:50:15.660Z        error   mlog/log.go:175 Unable to activate plugin       {"plugin_id": "com.github.matterpoll.matterpoll", "error": "unable to start plugin: com.github.matterpoll.matterpoll: fork/exec plugins/com.github.matterpoll.matterpoll/server/dist/plugin-linux-amd64: permission denied", "errorVerbose": "fork/exec plugins/com.github.matterpoll.matterpoll/server/dist/plugin-linux-amd64: permission denied\nunable to start plugin`
#### Server configuration
**Operating system:**
k8s chart
**Mattermost version:**
5.23
**Matterpoll version:**
1.1.0
**Updated from an older Matterpoll version or fresh install:**

<details>
<summary>Mattermost server logs</summary>

```
2020-08-04T08:50:15.660Z        error   mlog/log.go:175 Unable to activate plugin       {"plugin_id": "com.github.matterpoll.matterpoll", "error": "unable to start plugin: com.github.matterpoll.matterpoll: fork/exec plugins/com.github.matterpoll.matterpoll/server/dist/plugin-linux-amd64: permission denied", "errorVerbose": "fork/exec plugins/com.github.matterpoll.matterpoll/server/dist/plugin-linux-amd64: permission denied\nunable to start plugin
```
</details>

**Comment by erezo9** [comment]
you need to save the release with the dist as executable, the only one with execution mark is the windows one
i extracted the files, chmod +x  com.github.matterpoll.matterpoll/server/dist/plugin-linux-amd64
the archived it to tar.gz then uploaded, and then it worked

**Comment by hanzei** [comment]
I have issues reproducing your issue. For the latest release 1.3.0 the permissions work fine:
```
$ ls -lisa server/dist/
total 57304
176     0 drwxr-xr-x 2 sumacheb sumacheb      100 22. Okt 2019  .
175     0 drwxr-xr-x 3 sumacheb sumacheb       60 22. Okt 2019  ..
177 19068 -rwxr-xr-x 1 sumacheb sumacheb 19523120 22. Okt 2019  plugin-darwin-amd64
178 19312 -rwxr-xr-x 1 sumacheb sumacheb 19771658 22. Okt 2019  plugin-linux-amd64
179 18924 -rwxr-xr-x 1 sumacheb sumacheb 19375104 22. Okt 2019  plugin-windows-amd64.exe
```

**Comment by erezo9** [comment]
well i guess my download was faulty, downloaded again an it was fine
closing it, ty for the answer have a great weekend
