### ISSUE TITLE
Jump to poll when poll has ended opens Mattermost in browser instead of scrolling to poll in client

### ISSUE THREAD

**Issue by benjaminclauss** [matterpoll/matterpoll#324]
#### Summary
Jump to poll when poll has ended opens Mattermost in browser instead of scrolling to poll in client.

#### Steps to reproduce
1. Create and end poll.
2. Click "here" in "The poll [...] has ended and the original post has been updated. You can jump to it by pressing here."

#### Expected behavior
Not sure if it is possible but ideally scroll to the poll in the Mattermost client.

#### Observed behavior (that appears unintentional)
It opens the channel for the server in the browser.

#### Server configuration
**Operating system:** macOS Catalina 10.15.6

**Mattermost (client) version:** 4.5.2.6864
**Mattermost version:** 5.27.1

**Matterpoll version:** Unsure

**Comment by kaakaa** [comment]
Are you specifying the same URL for the preference of Mattermost client (desktop app)  and Site URL of mattermost-server?

* Preference of Mattermost client: **Mattermost > Preferences... > Server Management**
* Site URL of Mattermost-server: **System Console > Web Server > Site URL**
  * Site URL is used as link url of `here` in end poll post
  * e.g.: `${SiteURL}/_redirect/pl/5w93h36gejbsjp16xe97ikk6aa`

If these urls are same, client try to open link in client. If not, client open link in external browser. (I don't know a much about client, but that's how it seems to work in my environment.)

**Comment by hanzei** [comment]
@benjaminclauss Are you using the browser or the Desktop app?

**Comment by benjaminclauss** [comment]
@hanzei I am using the Desktop app.

**Comment by benjaminclauss** [comment]
> If these urls are same, client try to open link in client. If not, client open link in external browser. (I don't know a much about client, but that's how it seems to work in my environment.)

I don't fully understand this response. Are you saying that the client **Server URL** needs to be set in a way that enables the client to scroll up to the poll as opposed to opening Mattermost in a browser?

**Comment by kaakaa** [comment]
In some situations, yes. This is a possibility, but if the URL of the Mattermost server set in the Desktop App is different from the SiteURL, the link generated by Matterpoll will be recognized by the Desktop App as an external site and Desktop app will try to open it in an external browser.

![スクリーンショット 2020-11-19 15 23 44](https://user-images.githubusercontent.com/1453749/99630926-07cc2f80-2a7e-11eb-9cbe-d181c96732be.png)

**Comment by benjaminclauss** [comment]
I apologize for the delayed responses on this thread. This issue seems to have been due to a two-name issue with the Mattermost server configuration. It has now been resolved. I can do my best to answer any follow-up questions.
