### ISSUE TITLE
Migrate plugin/plugin.go to use mattermost-plugin-api

### ISSUE THREAD

**Issue by hanzei** [matterpoll/matterpoll#350]
https://github.com/mattermost/mattermost-plugin-api provided an plugin API without model.AppError that is developed independently of the Mattermost server. This ticket is about migrating `plugin/plugin.go` to use that package. Mocking for tests should happen with https://github.com/golang/mock.

**Comment by kaakaa** [comment]
https://github.com/mattermost/mattermost-plugin-api has been moved into mattermost/mattermost as monorepo. Close this and create new one as #500.
