### ISSUE TITLE
Provide instructions/link for offline install

### ISSUE THREAD

**Issue by ducttapecoder-vt** [matterpoll/matterpoll#369]
Attempting to obtain the plugin from  [Mattermost Integrations page](https://integrations.mattermost.com/?s=Matterpoll%20Plugin) leads back to github with nothing but 

>In Mattermost, open Main Menu > Plugin Marketplace to install and configure Matterpoll.

For offline/air gapped servers the Plugin Marketplace is inaccessible. Instructions or a link to download the necessary .gz file for upload would be helpful.

**Comment by ducttapecoder-vt** [comment]
Okay, I found the tar.gz download at https://github.com/matterpoll/matterpoll/releases but an upgrade procedure would be helpful.

**Comment by ducttapecoder-vt** [comment]
Okay looks like upgrade is as simple as importing the latest .tar.gz and accepting overwrite of the duplicate ID. I've created a PR for the documentation: https://github.com/matterpoll/matterpoll/pull/370

**Comment by kaakaa** [comment]
closed by #370 

Thanks for reporting and fix it!
