### ISSUE TITLE
Icon missing for past polls: 404 on logo_dark.png

### ISSUE THREAD

**Issue by bbodenmiller** [matterpoll/matterpoll#371]
#### Summary
Past polls appear to be expecting an icon at `/plugins/com.github.matterpoll.matterpoll/logo_dark.png` but it appears to no longer exist there

#### Steps to reproduce
1. Upload an older copy of plugin
2. Create poll
3. Upgrade to 1.4.0

#### Expected behavior
All instances of bot user should have icon

#### Observed behavior (that appears unintentional)
![image](https://user-images.githubusercontent.com/1192780/108326329-f7ac1500-717e-11eb-92c5-bed7a2b834cb.png)

#### Server configuration
**Operating system:** RHEL

**Mattermost version:** 5.27.0

**Matterpoll version:** 1.4.0

**Updated from an older Matterpoll version or fresh install:** From 1.3.0. Unclear when issue started.

**Comment by hanzei** [comment]
Do you see any errors in the server or webapp logs?

**Comment by bbodenmiller** [comment]
@hanzei I'll have to look. To be clear, new posts from bot user show icon just fine. It's only posts from awhile ago with an icon issue.

**Comment by bbodenmiller** [comment]
@hanzei no errors. All I see is

```json
{"level":"debug","ts":1614387244.0593662,"caller":"mlog/sugar.go:15","msg":"New request:","plugin_id":"com.github.matterpoll.matterpoll","Host":"mattermostdev.web.boeing.com","RequestURI":"/plugins/com.github.matterpoll.matterpoll/logo_dark.png","Method":"GET"}
```

**Comment by bbodenmiller** [comment]
![image](https://user-images.githubusercontent.com/1192780/109370078-ad4c2780-7853-11eb-8570-4fb41bb932f4.png)

**Comment by kaakaa** [comment]
There are no updates, so close this. If you continue to encounter this issue, feel free to reopen.

**Comment by bbodenmiller** [comment]
What do you mean no updates? I answered the questions asked.
