### ISSUE TITLE
Make Answers buttons visually distinguishable from administrative buttons

### ISSUE THREAD

**Issue by tmotyl** [matterpoll/matterpoll#373]
#### Make Answers buttons visually distinguishable from administrative buttons

Right now butons used to vote have the same style as buttons "add option" "remove poll" "end poll".
Buttons with answers are also wrapped in the same line, which makes it confusing to find all the answers when you have short answers and long answers.

**Comment by kaakaa** [comment]
Thanks for your comments. We're tackling this issue on #267. If you have any ideas, please comment your ideas in #267. And you may also be able to mitigate this problem somewhat by using the [Experimental UI setting](https://github.com/matterpoll/matterpoll#settings).

**Comment by kaakaa** [comment]
#267 is merged, and answer buttons and administrative buttons are now more easily distinguishable.
<img width="1123" alt="スクリーンショット 2023-02-02 23 32 59" src="https://user-images.githubusercontent.com/1453749/216352926-2c7c53b5-2a44-44c6-b962-0a9cdf22b5a9.png">

If you have any other comments, feel free to reopen this.
