### ISSUE TITLE
Poor experience on iOS Mobile due to smart punctuation

### ISSUE THREAD

**Issue by jl386** [matterpoll/matterpoll#376]
#### Summary
When using the mobile client double hypen is being converted to em dash preventing polls with settings.

#### Steps to reproduce
1. Create a poll on Mattermost mobile (iOS) with one or more poll setting(s)
2. In the message box note that the double hyphen (--) is being auto-converted to em dash (—) by default in iOS
3. Submit the poll and see the error that it does not recognise the setting

#### Expected behavior
Matterpoll should accept em dash (—) as a valid operator to flag the setting
Users should not need to think about manually overriding back to double-hypen or disabling Smart Punctuation on iOS

#### Server configuration
**Operating system:**
iOS

**Mattermost version:**
latest

**Matterpoll version:**
1.4.0

**Comment by hanzei** [comment]
https://github.com/mattermost/mattermost-mobile/pull/5259 will replace all em dashes with `--` and is scheduled for the next mobile release. Does that solve your issue?

**Comment by kaakaa** [comment]
This issue seems to be fixed in latest mobile app (v1.44.0). Thanks for reporting.

https://user-images.githubusercontent.com/1453749/122931424-d87cf880-d3a7-11eb-9f9b-87c919bb87f8.MP4
