### ISSUE TITLE
Plugin fails to start

### ISSUE THREAD

**Issue by pensatocriminale** [matterpoll/matterpoll#377]
#### Summary
After recent Mattermost server upgrade, plugin fails to start

#### Steps to reproduce
Steps to reproduce the behaviour:
Attempting to enable plugin via 'System Console' > 'Plugin Management' results in `This plugin failed to start. Check your system logs for errors.` message.

#### Expected behaviour
Plugin can be stopped/started from 'Plugin Management' without error.

#### Server configuration
**Operating system:**
Debian linux

**Mattermost version:**
5.33.1

**Matterpoll version:**
1.40

**Updated from an older Matterpoll version or fresh install:**
Updated

<details>
<summary>Mattermost server logs</summary>
```
{"level":"error","ts":1616720191.9121125,"caller":"mlog/log.go:232","msg":"Unable to activate plugin","plugin_id":"com.github.mat
terpoll.matterpoll","error":"failed to ensure bot user: failed to patch bot: SqlBotStore.Get: Bot does not exist., "}```
</details>

#### Additional context
Matterpoll was working normally for many months prior to recent mattermost server upgrade (5.25-LTS > 5.32.1), then after the upgrade it stopped working.  Issues reported to be related to profile image -
```
{"level":"error","ts":1615856055.1754315,"caller":"mlog/log.go:232","msg":"Unable to activate plugin","plugin_id":"com.github.matterpoll.matterpoll","error":"failed to ensure bot user: failed to set profile image: SetProfileImage: Couldn't upload profile image., "}
```
After some trouble-shooting steps related to permissions of user data, plugin permissions and other things, the plugin was removed and the 'matterpoll' user was deleted, then re-created manually.  The plugin was re-installed, but is still unable to start (bot account creation is enabled).

Server has been upgraded to 5.33.1 in between times.

I'm assuming the removal of the 'matterpoll' user wasn't the right thing to do, but am wondering if there are other things in the DB that need to be modified/removed to enable the plugin to re-create the required matterpoll user.  Any advice on that?

**Comment by steffenteichmann** [comment]
Have the same problem updated to 5.33.2

**Comment by kaakaa** [comment]
Thanks for reporting @pensatocriminale . It might be caused that `pluginkeyvaluestore` table still store old bot user id.
refs: https://github.com/matterpoll/matterpoll/issues/367#issuecomment-758723039

I don't know of any other way to delete this data for fixing this, but it doesn't seem to be good way. I'll report this to Mattermost itself.

**Comment by hanzei** [comment]
How did you remove the Matterpoll bot account? That isn't possible via the UI.

**Comment by pensatocriminale** [comment]
Thanks, I'll check it out.

 I deleted the bot user account manually, using `mattermost user delete`, thinking this may help in some way.  I added the account back manually after removing it, and changed its type to `bot`, but that didn't help things (due I think to this other linkage issue)

**Comment by hanzei** [comment]
Actually, the error `failed to ensure bot user: failed to set profile image: SetProfileImage: Couldn't upload profile image.,` is thrown in https://github.com/mattermost/mattermost-server/blob/d2e269edd281017f2013f2542bcc59f000b8878f/app/user.go#L1014. Unfortunately, the original error isn't getting logged. I will add it to allow easier debugging.

**Comment by pensatocriminale** [comment]
`DELETE FROM pluginkeyvaluestore WHERE pluginid = 'com.github.matterpoll.matterpoll';` followed by removal/re-installation of the plugin (1.4.0) has things working again - thanks!

**Comment by hanzei** [comment]
Thanks for posting that solution @pensatocriminale :+1: 

Closing

**Comment by akiross** [comment]
I'm having the same problem with latest matterpoll (1.6.1) and mattermost 9.3.0. I tried the solution specified above to no avail.
