### ISSUE TITLE
Layout of result view b0rked

### ISSUE THREAD

**Issue by p3k** [matterpoll/matterpoll#391]
#### Summary
Presumably after the last Mattermost upgrade the right column of a poll’s results view looks vertically misaligned.

#### Steps to reproduce
1. Create and run a Matterpoll with a few options
2. End the poll

![image](https://user-images.githubusercontent.com/16631/125270075-9d684800-e309-11eb-8d59-77b4bc4396b8.png)

#### Server configuration
**Operating system:** Linux

**Mattermost version:**  5.34.4

**Matterpoll version:** 1.4.0

**Comment by hanzei** [comment]
Thanks for the report. This might be an issue within Mattermost. See https://community-daily.mattermost.com/core/pl/dj1fhxqp77rgfkxnmenkbx5hnh for the discussion.

**Comment by hanzei** [comment]
Fixed in https://github.com/mattermost/mattermost-webapp/pull/8534
