### ISSUE TITLE
Locally built plugin isn't starting after uploading to Mattermost

### ISSUE THREAD

**Issue by KhaimovMR** [matterpoll/matterpoll#393]
#### Summary
Bug report in one concise sentence

#### Steps to reproduce
1. Checkout to the 1.4.0 version in repo
2. `gvm use go1.14; nvm use v14.12.0`
3. `make build`
4. Upload built 1.4.0 tar gz to MM server 
5. click Enable button on the plugin on the Plugins Management page.

OS: Ubuntu 20.04

#### Expected behavior
Describe your issue in detail

#### Observed behavior (that appears unintentional)
Plugin unable to activate - returns the error, showed in log below.

#### Server configuration
**Operating system:**

**Mattermost version: 5.37.0**

**Matterpoll version: 1.4.0**

**Fresh install**

<details>
<summary>Mattermost server logs</summary>

```
 {    
     "level": "error",    
     "ts": 1627473495.9108639,    
     "caller": "mlog/log.go:251",    
     "msg": "Unable to activate plugin",    
     "plugin_id": "com.github.matterpoll.matterpoll",    
     "error": "unable to start plugin: com.github.matterpoll.matterpoll: Unrecognized remote plugin message: \n\nThis usually means that the plugin is either invalid or simply\nneeds to be recompiled to support the latest protocol.",        
     "errorVerbose": "Unrecognized remote plugin message: \n\nThis usually means that the plugin is either invalid or simply\nneeds to be recompiled to support the latest protocol.\nunable to start plugin: com.github.matterpoll.matterpoll\ngithub.com/mattermost/mattermost-server/v5/plugin.(*Environment).Activate\n\tgithub.com/mattermost/mattermost-server/v5/plugin/environment.go:274\ngithub.com/mattermost/mattermost-server/v5/app.(*Server).syncPluginsActiveState.func2\n\tgithub.com/mattermost/mattermost-server/v5/app/plugin.go:144\nruntime.goexit\n\truntime/asm_amd64.s:1374"                                                                                                                                                                                       
 }
```
</details>

**Comment by hanzei** [comment]
Can you install the plugin successfully using the bundle provided via GitHub?

**Comment by rbino** [comment]
@hanzei I just reproduced this, I built from current `master` to test the progress feature, the plugin gets built but if I load it in Mattermost if fails with:
```
{"timestamp":"2022-11-29 10:55:24.602 Z","level":"info","msg":"plugin process exited","caller":"plugin/hclog_adapter.go:61","plugin_id":"com.github.matterpoll.matterpoll","wrapped_extras":"pathplugins/com.github.matterpoll.matterpoll/server/dist/plugin-linux-amd64pid127"}
{"timestamp":"2022-11-29 10:55:25.830 Z","level":"warn","msg":"plugin failed to exit gracefully","caller":"plugin/hclog_adapter.go:72","plugin_id":"com.github.matterpoll.matterpoll"}
{"timestamp":"2022-11-29 10:55:25.830 Z","level":"error","msg":"plugin process exited","caller":"plugin/hclog_adapter.go:79","plugin_id":"com.github.matterpoll.matterpoll","wrapped_extras":"pathplugins/com.github.matterpoll.matterpoll/server/dist/plugin-linux-amd64pid165errorexit status 1"}
{"timestamp":"2022-11-29 10:55:25.858 Z","level":"error","msg":"Unable to restart plugin on upgrade.","caller":"web/context.go:117","path":"/api/v4/plugins","request_id":"y874nnino7bf9qmeyawsefxrhy","ip_addr":"10.52.2.2","user_id":"6m1jajnmi3ncjq9wqz5fromeih","method":"POST","err_where":"installExtractedPlugin","http_code":500,"error":"installExtractedPlugin: Unable to restart plugin on upgrade., unable to start plugin: com.github.matterpoll.matterpoll: Unrecognized remote plugin message: \n\nThis usually means that the plugin is either invalid or simply\nneeds to be recompiled to support the latest protocol."}
```

The Github bundle was working fine before.

The plugin was compiled locally with Go 1.18, nodejs 13.14.0.
Mattermost version: 7.3.0 (Enterprise edition), Database Schema Version: 92.

Let me know if there's any other way I can build the plugin to test the new feature

**Comment by hanzei** [comment]
Could you please set the environment variable `CGO_ENABLED=0` before building the plugin yourself?

**Comment by rbino** [comment]
@hanzei with `CGO_ENABLED=0` it works. Should build instructions in `CONTRIBUTING.md` be updated?

**Comment by hanzei** [comment]
I would much rather downstream the changes from the starter-template: https://github.com/mattermost/mattermost-plugin-starter-template/commit/2474dfc8034ce31c4eb010d0aa54569e403bd964

**Comment by kaakaa** [comment]
`CGO_ENBALED=0` have been added to `Makefile` by #487 . And I'll close this issue as originally reported issue is on old environment and I don't have capacity to support old version.
