### ISSUE TITLE
Not able to install on MM 6.0.2

### ISSUE THREAD

**Issue by dragonpil** [matterpoll/matterpoll#401]
#### Summary
When I try to install this plugin with MM 6.0.2 server I get:
Unable to move plugin from temporary directory to final destination. Another plugin may be using the same directory name.

#### Steps to reproduce
1. Go to Marketplace
2. Click on install next to matter poll

3. See error: Unable to move plugin from temporary directory to final destination. Another plugin may be using the same directory name.

#### Expected behavior
Plugin is installed.

**Comment by dragonpil** [comment]
Thanks Issue solved... 
Problem was that mattermost/plugins contained old matter poll plugin (from before upgrade)

**Comment by kaakaa** [comment]
Glad to hear that your issue was resolved. I'll close this.
