### ISSUE TITLE
Windows Desktop client crashing with Matterpoll plugin enabled

### ISSUE THREAD

**Issue by adjurk** [matterpoll/matterpoll#403]
#### Summary

One of our users on a self-hosted Mattermost 6.1.0 server has reported that when launching her Desktop client on Windows, she can only see a blank/white page, signaling the app can't load. Application wrapper logs reveal there might be an issue with loading Matterpoll.

#### Steps to reproduce

Steps to reproduce the behavior - specific to the user, it seems:

1. Open Mattermost Desktop app on Windows
2. After a moment of loading, a blank screen is shown to the user and nothing else is happening.

#### Expected behavior

Mattermost app loads normally.

#### Observed behavior (that appears unintentional)

Mattermost Desktop app's screen is white/blank.

#### Server configuration
**Operating system:** Windows 10 Pro (Build: 19042.1415)

**Mattermost version:** 6.1.0

**Matterpoll version:** 1.4.0

**Updated from an older Matterpoll version or fresh install:** unsure, but I don't think we updated Matterpoll yet, so I think it's a fresh install

<details>
<summary>Mattermost server logs</summary>
Unsure what logs are we looking for - couldn't find applicable.
</details>

#### Additional context
DevTools Console tab from Mattermost Desktop app's Application Wrapper:
![Screenshot_8](https://user-images.githubusercontent.com/13603158/146782984-bce80c6d-6917-4748-8935-13a632b9898b.png)

The affected user has also reported they've tried installing an older `4.6.0` Desktop app version but it didn't help, so they've reinstalled the latest one.

**Comment by kaakaa** [comment]
Thanks for reporting @adjurk. 
The following issue seems to be same as yours, and it has fixed in Mattermost v.6.2. Could you please try again after upgrading your mattermost-server to v6.2?

* https://github.com/mattermost/mattermost-server/issues/19095

**Comment by adjurk** [comment]
Hi @kaakaa

Sorry for a late update - we've re-enabled Matterpoll after upgrading out Mattermost Server instance and everything seems to be working up for the user up to today :) Thanks for your help!
