### ISSUE TITLE
Please add to Mattermost Plugin Marketplace

### ISSUE THREAD

**Issue by bbodenmiller** [matterpoll/matterpoll#413]
https://developers.mattermost.com/integrate/plugins/community-plugin-marketplace/#process-for-adding-a-community-plugin-to-the-marketplace

**Comment by kaakaa** [comment]
Matterpoll can already be found in Plugin Marketplace as a community plugin.
![E2F5423A-179F-4C9F-8392-11E67DF45BD4](https://user-images.githubusercontent.com/1453749/155726489-3dee0ea3-3e58-480d-9317-17893bb05480.jpeg)

Is it not showing up in your environment?

**Comment by bbodenmiller** [comment]
Appears somethings wrong though as it does not show updates:

![image](https://user-images.githubusercontent.com/1192780/189255915-40e267d8-6a8d-42a4-a339-9606abd0c5b6.png)

Like I see for other plugins:

![image](https://user-images.githubusercontent.com/1192780/189255941-6c38bd8f-7e2e-4b00-8c39-e45d4b5feaad.png)

**Comment by kaakaa** [comment]
Thanks @bbodenmiller 
It would not be wrong. I've created a new release of Matterpoll v1.5.0, but the process for updating plugin in the Marketplace is stopping. The update of Matterpoll will not appear until the process is completed.

Please follow the following issue/message about the process for updating plugin in the Marketplace.
https://github.com/mattermost/mattermost-marketplace/issues/298
#448 
https://community.mattermost.com/core/pl/jj6bfcwbbbgffjj458stdncmyc

**Comment by bbodenmiller** [comment]
Thanks for the update! Sorry to hear they are taking so long.

**Comment by kaakaa** [comment]
Mattermost v1.5.0 is now available through marketplace.
https://github.com/mattermost/mattermost-marketplace/issues/298#issuecomment-1412129672
