### ISSUE TITLE
Poll leaks full name of creator when full names are disabled on a server level

### ISSUE THREAD

**Issue by Morthy** [matterpoll/matterpoll#440]
When "Show Full Name" is set to false in the System Console under "Users and teams", creating a poll shows the full name of the creator instead of only their username.

![image](https://user-images.githubusercontent.com/5537959/182162903-ebc079b4-dc5f-41e9-bc7e-2e7ff7871b90.png)

#### Steps to reproduce
1. Set "Show Full Name" to false
2. Create a poll
3. On browser, observe that the creator name shows their full name

#### Expected behavior
The full name should not be shown

#### Server configuration
**Operating system:** Linux

**Mattermost version:** 7.1.2

**Matterpoll version:**  1.5.0

**Updated from an older Matterpoll version or fresh install:** Updated

#### Additional context

It looks like the problem stems from here: https://github.com/matterpoll/matterpoll/blob/master/server/plugin/plugin.go#L165

**Comment by kaakaa** [comment]
Thank you for reporting @Morthy . This should be fixed, and I'm working on this. #442
