### ISSUE TITLE
don't  find  github.com/stretchr/testify/mock  

### ISSUE THREAD

**Issue by gleke** [matterpoll/matterpoll#454]
#### Summary
don't  find  github.com/stretchr/testify/mock  

Why use mock sore , and what is its function? I can't get it now in github

**Comment by hanzei** [comment]
The package `github.com/stretchr/testify/mock` is available via https://github.com/stretchr/testify and used in the code base for test mocks.

**Comment by kaakaa** [comment]
There are no updates, so close this. If having any updates, feel free to reopen.
