### ISSUE TITLE
After a vote is cast, the option that was selected is not visible under most of the preset Mattermost themes

### ISSUE THREAD

**Issue by dylanhs** [matterpoll/matterpoll#464]
#### Summary
After I cast a vote in a Matterpoll poll, I cannot see the text for the option I selected unless I mouse over it. This seems to stem from the fact that Matterpoll uses "Link Color" for the unselected options and "Button text color" for the selected option, so any theme where "Button Text" and "Center Channel BG" are similar will suffer from this problem. This affects all of the preset Mattermost themes except for the "dark mode" ones (Indigo and Onyx).

#### Steps to reproduce
1. Set Mattermost theme to any "light-mode" theme (Denim, Sapphire, or Quartz)
2. Create a poll
3. Vote in poll
4. Notice the text for the selected option is not visible unless you mouse over it

#### Expected behavior
Ideally, I think the text should be visible for whatever option I selected after I cast a vote, regardless of whether I'm mousing over it or not.

#### Observed behavior (that appears unintentional)
The selection is not visible unless I mouse over it.

#### Server configuration
**Operating system:** Windows 10

**Mattermost version:** 7.4.0

**Matterpoll version:** 1.4.0

**Updated from an older Matterpoll version or fresh install:** unknown

**Comment by kaakaa** [comment]
Thanks @dylanhs .
This issue is similar to #452 #402, and would be fixed in v1.5.0. See details in https://github.com/matterpoll/matterpoll/issues/452#issuecomment-1252347075.

**Comment by kaakaa** [comment]
Mattermost v1.5.0 is now available through marketplace, and this should be fixed.
https://github.com/mattermost/mattermost-marketplace/issues/298#issuecomment-1412129672
