### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by q-wertz** [matterpoll/matterpoll#474]
#### Summary

Could you release a new version and make it available over the Plugin Store? Especially #431 would be very beneficial. :blush: 

#### Describe alternatives you've considered

Install the git repo version

**Comment by danieljuschus** [comment]
Indeed, I would love to have https://github.com/matterpoll/matterpoll/pull/431 too.

**Comment by kaakaa** [comment]
Thank you for requesting new version. I created an issue for releasing 1.6.0 #476, and will close this because the release process can track in it.
