### ISSUE TITLE
Font issue: small letter i is displayed as I

### ISSUE THREAD

**Issue by e1kable** [matterpoll/matterpoll#486]
#### Summary
The utilized font visualizes text ambiguously.

#### Steps to reproduce
/poll "small i big I; small l big L" "yes" "no"
![grafik](https://github.com/matterpoll/matterpoll/assets/59206940/214f1620-c5cd-43c4-b35d-112a54cf823d)

#### Expected behavior
Expected a proper small i

#### Observed behavior (that appears unintentional)
Got the ambigous character I

#### Server configuration
**Operating system:**
Linux-Ubuntu

**Mattermost version:**
 7.1.5

**Matterpoll version:**
1.5.0

**Updated from an older Matterpoll version or fresh install:**
fresh

**Comment by kaakaa** [comment]
@e1kable  Thanks for your reports. Matterpoll doesn't change type-family, and follows Mattermost's font. So I suppose that this issue is caused by Mattermost or your browser setting.

In my local, `Metropolis Semi Bold` is used here, and it can't reproduce this issue. Also, the `Metropolis` font seems to be specified by Mattermost.
![スクリーンショット 2023-05-13 14 02 49](https://github.com/matterpoll/matterpoll/assets/1453749/375851d4-d828-4047-9dbe-9a6b9ba7405a)

What type of font is your browser using?

**Comment by e1kable** [comment]
Interesting! In my MM version it's the font Metropolis which causes the problem. Which MM version are you using?
![grafik](https://github.com/matterpoll/matterpoll/assets/59206940/37977675-b1ad-49d6-b614-820cd714aa9d)

**Comment by kaakaa** [comment]
Hmm... I set up the same version of MM (v7.1.5) by using [official docker](https://github.com/mattermost/docker), and installed Matterpoll 1.5.0 via MM marketplace. I'm accessing to MM via chrome, firefox, and safari on macos, but it seems to be fine at all.
<img width="1267" alt="スクリーンショット 2023-05-13 21 46 09" src="https://github.com/matterpoll/matterpoll/assets/1453749/4bdd9c94-e4ef-465f-8695-f15f85158f87">

If you create the simple post with a message such as `# small i large I`, it would be rendered as a heading with h1 tag, and applied the same font-family as the sentence of poll. If `i` in the heading is rendered as an uppercase I, it seems to be an issue with MM as a whole or with the environment.

**Comment by e1kable** [comment]
Hey, thank you for your replies. I think I found the error. When I increase my screen scale (125%) the i starts to appear. I'm on Windows 11. Respectively, when I change the font size in CSS. At exactly 14px the dot disappears...
**font-size: 13px;**
![grafik](https://github.com/matterpoll/matterpoll/assets/59206940/e78c5e1e-30c8-4fb6-ad74-d353cfea4d34)

**font-size: 14px;** (default)
![grafik](https://github.com/matterpoll/matterpoll/assets/59206940/d948854b-9493-41e5-96c9-cc765414233f)

**font-size: 15px;**
![grafik](https://github.com/matterpoll/matterpoll/assets/59206940/0ad08e47-2ded-4931-9503-e5dd3c7ed372)

**Comment by kaakaa** [comment]
Thanks! It's completely weird, but I'm glad that you have found the cause anyway.
