### ISSUE TITLE
Inconsistent capitalization between "Reset your vote" and "Add Option", "End Poll", "Delete Poll" etc

### ISSUE THREAD

**Issue by dllu** [matterpoll/matterpoll#497]
#### Summary

Whereas "Reset your vote" only has the first letter of the first word capitalized, the other three options have the first letter of all words capitalized.

#### Steps to reproduce

Create a poll.

#### Expected behavior

The "Reset your vote" button should have a similar capitalization style as the other buttons.

#### Observed behavior (that appears unintentional)

The capitalization is inconsistent.

![image](https://github.com/matterpoll/matterpoll/assets/14482624/d2ee0a5d-3e07-469c-8470-7d528fbfd886)

#### Server configuration
**Operating system:** no idea

**Mattermost version:** 7.10.3

**Matterpoll version:** idk but a quick look on github shows that the issue persists

**Updated from an older Matterpoll version or fresh install:** idk

#### Additional context

There are some other "Something went wrong" bugs when I try to vote but I'm not sure what causes them so I am not going to make a bug report for that.

**Comment by hanzei** [comment]
Good catch @dllu :+1:

**Comment by chandansgowda** [comment]
Hey @hanzei 
Can I take this up ?

**Comment by hanzei** [comment]
Sure :+1:

**Comment by chandansgowda** [comment]
Thanks @hanzei 
Can you please point me to resources which will help me work on the issue as well as contribute to the project in future ?

**Comment by hanzei** [comment]
https://github.com/matterpoll/matterpoll/blob/master/CONTRIBUTING.md is a good starting point. Please let me know if you have any specific questions.

**Comment by chandansgowda** [comment]
Hey @hanzei 
Code style tests are failing. Can you please help me with that?
