### ISSUE TITLE
Release plugin.json does not specify path to arm build

### ISSUE THREAD

**Issue by DanielHeath** [matterpoll/matterpoll#525]
#### Summary
Arm builds of this plugin are broken because plugin.json doesn't specify the path to the binary.

#### Steps to reproduce

Unzip the release package on an arm linux instance and try to enable it.

Mattermost fails to enable the plugin, because plugin.json doesn't specify where to find the binary.

**Comment by hanzei** [comment]
What is the error you are seeing? There should be a binary for arm54: https://github.com/matterpoll/matterpoll/blob/f0df90060e73cca6c993c1d9dba919b2f4998456/Makefile#L77C2-L77C2

**Comment by DanielHeath** [comment]
Looking further, this was fixed last month in https://github.com/matterpoll/matterpoll/pull/520 but that change is not in the latest release (which dates to May). 

Looks like making a new release will resolve the issue for anyone on ARM.

**Comment by kaakaa** [comment]
@DanielHeath I've released [v1.7.0](https://github.com/matterpoll/matterpoll/releases/tag/v1.7.0) including #520, and it can fix this issue. If you still encounter the same with v1.7.0, feel free to reopen this.
