### ISSUE TITLE
Release 0.1.0

### ISSUE THREAD

**Issue by Hanzei** [matterpoll/matterpoll#54]
Since v0.0.3 there have been a lot of improvements. I think its time to cut v0.1.0 soon.

I would like to get the following PR in:
- ~~#46~~
- #49
- #53 

My plan is to cut the release at the 17th. Then I would also post about this on https://forum.mattermost.org/c/plugins.

**Comment by Hanzei** [comment]
https://github.com/buchanae/github-release-notes/ would be used to create the changelog.

**Comment by kaakaa** [comment]
I agree with releasing v0.1.0 and your suggested schedule 👍
And I'm okay with buchanae/github-release-notes.
