### ISSUE TITLE
Release plan?

### ISSUE THREAD

**Issue by Uatschitchun** [matterpoll/matterpoll#542]
Let me start with: it's done when it's done. That's for sure ;)

As there are some things going on in PRs, is there any plan on what the next release will be and should go into and what's missing?

**Comment by kaakaa** [comment]
Thank you for your comment @Uatschitchun . I've just started work on the release (#543). I'm going to release a new version v1.7.0 after we have had a period of time to update the translations after some PRs that are in progress now are completed. It may take a bit more time, so please bear with me for a moment.

**Comment by Uatschitchun** [comment]
Thx for answering! No problem with waiting. As said, it's done when it's done!
Could help with german translation, if needed.

**Comment by kaakaa** [comment]
The release process for v1.7 has started on #546.

**Comment by kaakaa** [comment]
@Uatschitchun If you have a time, I'm glad for you to update German translation. #546

**Comment by Uatschitchun** [comment]
> @Uatschitchun If you have a time, I'm glad for you to update German translation. #546

Done. See #552
