### ISSUE TITLE
Add unique prefix to DB keys

### ISSUE THREAD

**Issue by hanzei** [matterpoll/matterpoll#59]
We store polls into the DB by using `pollID` as a key. This limits our DB to only containing polls. By adding a prefix e.g. `pollID_` to the key, we avoid this problem.

This would of cause break all previous polls. But we are still early in development and I don't consider this a blocking problem.

This should be done before v1.0

**Comment by Hanzei** [comment]
Let's talk technical here.

I propose to add a new package called `store` and a a `store` field to `MatterpollPlugin`. This way we can separate storing data from using data. And it makes unit tests easier.
A `store` would have have different methods for storing different kind of information like `StorePoll()` or `StoreVersion` (See #62)`.
