### ISSUE TITLE
Secure http requests

### ISSUE THREAD

**Issue by hanzei** [matterpoll/matterpoll#61]
API requests are currently not secured by any kind of application level security. The only security comes from https, if the server is configured correctly. Security is bound to knowing a polls ID. 

We could generate a secure token via plugin settings and include this in every http payload. This would increase security.

Of course if would be backwards incompatible. But we could include a migration step.

**Comment by Hanzei** [comment]
I'm really not sure if the is needed. If the server doesn't use https, secure tokens in a payload wont help either. I don't see a case where this help. Do you @kaakaa?

**Comment by hanzei** [comment]
Closing this one, as it does't seams to be a smart idea.
