### ISSUE TITLE
Save Matterpoll version for migration 

### ISSUE THREAD

**Issue by hanzei** [matterpoll/matterpoll#62]
We should store the Matterpoll version in the DB. This allows us to do some kind of migration in future versions.

**Comment by Hanzei** [comment]
@kaakaa What do you think about this idea?

**Comment by kaakaa** [comment]
@Hanzei Sounds good, but I have a concern.

I think that the use case of Matterpoll version might be duplicated with the use case of DataSchemeVersion. The both are used for migrating poll data.

Do you have any exact use case of Matterpoll version?

**Comment by Hanzei** [comment]
I think storing the Matterpoll version is the foundation of a db migration. Currently we have to way to know if migration should happen. The migration flow I have in mind looks like this:

- On plugins start we get the Matterpoll version for the DB
- We check if its the latest one. 
- If it is, we are done.
- If not, we check if some kind of migration has to be done and do it. Then store the new Mattermost version in the DB.

Note that this is mostly taken from https://github.com/mattermost/mattermost-server/blob/master/store/sqlstore/upgrade.go.

A other use case for Matterpoll version besides DB upgrade is announcing new versions to users. This way we could inform users about e.g. new Poll Settings.

**Comment by kaakaa** [comment]
Thank you for clarifying use cases. I got it.

Now that we have `KVList` method, it sounds good to migrate DB when activating.
If this is implemented, I think DataSchemeVersion doesn't have any use case.
