### ISSUE TITLE
Getting error 400 with correct site URL

### ISSUE THREAD

**Issue by Twilek-de** [matterpoll/matterpoll#72]
Hi,

matterpoll displays correctly but the buttons do nothing and it generates an 400 Error. But my site URL is correct with https:// and all. I tried it with and without a trailing slash.

I use MM 5.3.1 and tried the Webinterface and the latest Ios Client. I restarted the Server between changes.

`
2018-09-24T19:02:26.418+0200    error   web/context.go:60       Action integration error        {"path": "/api/v4/posts/jmasdsa8asdfreqci5sxkbe/actions/sasdsad7uebkasjdsalkdhk9s5h7h", "request_id": "3jk3gjydkajsdlaskjcbq8x8c", "ip_addr": "95.x.x.x", "user_id": "3qasdsda3askldjaslkdja9ut98wo", "method": "POST", "err_where": "DoPostAction", "http_code": 400, "err_details": "status=400"}`

**Comment by Hanzei** [comment]
Thanks for the report @Twilek-de.

Are you using the latest version of Matterpoll? (0.1.0) Are you running it with Mattermost 5.3?

**Comment by Twilek-de** [comment]
I think I got it. It really was the trailing slash. But already existing Polls don´t update. Without the trialing Slash and with a new poll it now seems to work...

**Comment by Hanzei** [comment]
To recap: You Site URL had a trailing slash and removing it fixed your problem?

**Comment by Twilek-de** [comment]
Yes that is what it looks like. I have installed mattermost in the root directory so there is only the domain and no sub directory.

**Comment by Hanzei** [comment]
I would like to debug this a little further. In the `mattermost.log` there should be log messages about the poll creations. Would you please post them?

**Comment by Twilek-de** [comment]
Hmmm I don´t see any log messages for the poll creation. I can only see the 400 errors, maybe my log level is too low/high.

**Comment by Twilek-de** [comment]
But somehow although it works it still spawns errors from time to time...

`2018-09-24T22:08:41.727+0200    error   web/context.go:60       Action integration error        {"path": "/api/v4/posts/jms823545jkh432jhi5sxkbe/actions/kzwsjk234hk2j345hk32js98y", "request_id": "3i6ui7832j4h23jk4h23kj4h2kidw", "ip_addr": "x.x.x.x", "user_id": "q32jkh432kj4hkj3246do", "method": "POST", "err_where": "DoPostAction", "http_code": 400, "err_details": "status=400"}
`

**Comment by Twilek-de** [comment]
Okay I turned log level to DEBUG and created a poll which worked:

`2018-09-24T23:38:21.783+0200	debug	app/plugin_api.go:351	Created a new poll	{"plugin_id": "com.github.matterpoll.matterpoll", "response": "{\"response_type\":\"in_channel\",\"text\":\"\",\"username\":\"Matterpoll\",\"icon_url\":\"https://xxx.xxx.de/plugins/com.github.matterpoll.matterpoll/logo_dark.png\",\"type\":\"\",\"props\":null,\"goto_location\":\"\",\"attachments\":[{\"id\":0,\"fallback\":\"\",\"color\":\"\",\"pretext\":\"\",\"author_name\":\"twilek\",\"author_link\":\"\",\"author_icon\":\"\",\"title\":\"Test\",\"title_link\":\"\",\"text\":\"Total votes: 0\",\"fields\":null,\"image_url\":\"\",\"thumb_url\":\"\",\"footer\":\"\",\"footer_icon\":\"\",\"ts\":null,\"actions\":[{\"id\":\"\",\"name\":\"Yes\",\"type\":\"button\",\"data_source\":\"\",\"options\":null,\"integration\":{\"url\":\"https://xxx.xxx.de/plugins/com.github.matterpoll.matterpoll/api/v1/polls/7uzexnererttterftko/vote/0\"}},{\"id\":\"\",\"name\":\"No\",\"type\":\"button\",\"data_source\":\"\",\"options\":null,\"integration\":{\"url\":\"https://xxx.xxx.de/plugins/com.github.matterpoll.matterpoll/api/v1/polls/7uzen386erterret/vote/1\"}},{\"id\":\"\",\"name\":\"Delete Poll\",\"type\":\"button\",\"data_source\":\"\",\"options\":null,\"integration\":{\"url\":\"https://xxx.xxx.de/plugins/com.github.matterpoll.matterpoll/api/v1/polls/7uzefdggsdfsdfdsf4ftko/delete\"}},{\"id\":\"\",\"name\":\"End Poll\",\"type\":\"button\",\"data_source\":\"\",\"options\":null,\"integration\":{\"url\":\"https://xxx.xxx.de/plugins/com.github.matterpoll.matterpoll/api/v1/polls/sdfsdfdsfsdfsefew/end\"}}]}]}"}`

then I added the trailing slash to the site URL and created a poll which doesn´t work:

`2018-09-24T23:39:40.318+0200	debug	app/plugin_api.go:351	Created a new poll	{"plugin_id": "com.github.matterpoll.matterpoll", "response": "{\"response_type\":\"in_channel\",\"text\":\"\",\"username\":\"Matterpoll\",\"icon_url\":\"https://xxx.xxx.de//plugins/com.github.matterpoll.matterpoll/logo_dark.png\",\"type\":\"\",\"props\":null,\"goto_location\":\"\",\"attachments\":[{\"id\":0,\"fallback\":\"\",\"color\":\"\",\"pretext\":\"\",\"author_name\":\"twilek\",\"author_link\":\"\",\"author_icon\":\"\",\"title\":\"Test2\",\"title_link\":\"\",\"text\":\"Total votes: 0\",\"fields\":null,\"image_url\":\"\",\"thumb_url\":\"\",\"footer\":\"\",\"footer_icon\":\"\",\"ts\":null,\"actions\":[{\"id\":\"\",\"name\":\"Yes\",\"type\":\"button\",\"data_source\":\"\",\"options\":null,\"integration\":{\"url\":\"https://xxx.xxx.de//plugins/com.github.matterpoll.matterpoll/api/v1/polls/9m57nxfsdfsdfsdfvote/0\"}},{\"id\":\"\",\"name\":\"No\",\"type\":\"button\",\"data_source\":\"\",\"options\":null,\"integration\":{\"url\":\"https://xxx.xxx.de//plugins/com.github.matterpoll.matterpoll/api/v1/polls/9m57nxsdfsdf9jcbe/vote/1\"}},{\"id\":\"\",\"name\":\"Delete Poll\",\"type\":\"button\",\"data_source\":\"\",\"options\":null,\"integration\":{\"url\":\"https://xxx.xxx.de//plugins/com.github.matterpoll.matterpoll/api/v1/polls/9m57nxfsfsdfsdfde/delete\"}},{\"id\":\"\",\"name\":\"End Poll\",\"type\":\"button\",\"data_source\":\"\",\"options\":null,\"integration\":{\"url\":\"https://xxx.xxx.de//plugins/com.github.matterpoll.matterpoll/api/v1/polls/9m57nsdsdfsdzw9jcbe/end\"}}]}]}"}`

The generated URLs do have one slash too much after the domain. You should enter some function to trim a trailing slash from the URL.

**Comment by Hanzei** [comment]
Thanks @Twilek-de!

 I contacted a Mattermost employee on pre-release about this problem. The discussion can be found [here](https://pre-release.mattermost.com/core/pl/baumxj3j17d4dfr9wg4w9t38yh).

**Comment by Hanzei** [comment]
I submitted a PR https://github.com/mattermost/mattermost-server/pull/9463. Hopefully this will be fixed in Mattermost 5.4.
