### ISSUE TITLE
Permission for Admins to End or Delete Polls

### ISSUE THREAD

**Issue by Twilek-de** [matterpoll/matterpoll#74]
It would be nice not only for the creator of a poll but also for the admins to be able to end or to delete a poll.

**Comment by Hanzei** [comment]
@kaakaa if you think this is a good enchantment I would develop it

**Comment by kaakaa** [comment]
This feature sounds good 👍 
But at first, we should clarify whether the `admin` is system admins or team admins or channel admins. 
https://docs.mattermost.com/help/getting-started/managing-members.html#user-roles

I think that it should be only system admins, Beause only system_admin has `PERMISSION_EDIT_OTHERS_POSTS`.
https://github.com/mattermost/mattermost-server/blob/master/model/role.go#L334

@Twilek-de, @Hanzei How does it sounds?

**Comment by Twilek-de** [comment]
Sounds good, although I will only be able to test it partially as I am running a very small private installation of Mattermost with me as the only admin.
