### ISSUE TITLE
Future planing

### ISSUE THREAD

**Issue by hanzei** [matterpoll/matterpoll#78]
Development on Matterpoll is quite rapid at the moment. But I think its time to decide which changes we want to make before declaring this plugins stable and release Matterpoll 1.0. I propose to ditch v0.2 and release v1.0 as the next major release. Given that there a some fixes for plugins coming in Mattermost 5.4 I would plan to release Matterpoll 1.0 at the same time as 5.4 comes out.

#59 and #62 should go into v1.0, if we accept this ideas as good. If https://github.com/mattermost/mattermost-server/pull/9429 makes it into Mattermost 5.4 we could also use this.

@kaakaa Are you fine with releasing Matterpoll 1.0 soon? Are the more changes you want to make before this?

**Comment by kaakaa** [comment]
v1.0 sounds good :+1: 

I want to add #83 to v1.0. and archive `matterpoll-emoji` and direct users this repo.
