### ISSUE TITLE
Display indicators for anonymous settings

### ISSUE THREAD

**Issue by kaakaa** [matterpoll/matterpoll#83]
Anonymous setting doesn't change any UI until poll ends.
We should display any indicator for anonymous setting.

**Comment by hanzei** [comment]
Good idea. Maybe we could show a short text after the "Total votes" text? 
![screenshot from 2018-10-08 10-34-49](https://user-images.githubusercontent.com/16541325/46598995-4c86ed80-cae6-11e8-933e-5bd32a7dd90c.png)

**Comment by kaakaa** [comment]
Yes, your suggested style is what I came up. It's simple solution.

#### Simple style
<img width="872" alt="2018-10-09 22 05 44" src="https://user-images.githubusercontent.com/1453749/46671601-25c4d600-cc10-11e8-926a-a4792f11419d.png">

#### Markdown style
Then, I found that we can use markdown for SlackAttachment.Text field. So the next one looks good too.
<img width="884" alt="2018-10-09 22 05 27" src="https://user-images.githubusercontent.com/1453749/46671628-35441f00-cc10-11e8-9a6c-dc9a42243908.png">

#### Icon style
Additionally, we can serve new icon image for every settings, and display on poll post.

---

I like **Markdown style**, because question, meta information, answers are well separated.
Which do you like? or some other ideas?

**Comment by hanzei** [comment]
I agree with you. **Markdown style** looks great :+1: . My only concern is, that question and answer options are so far away and separated from each other. But this is just a minor note.

I would just show **Options** if there are any options set. Otherwise I would remove the word.

Keep in mind that we agreed on the term **Poll Settings**. So please change **Options** to **Poll Settings**.

**Comment by kaakaa** [comment]
> I would just show Options if there are any options set. Otherwise I would remove the word.

Sure 👍 

> Keep in mind that we agreed on the term Poll Settings. So please change Options to Poll Settings.

Oh...you are right. I'll be careful. Thank you for correcting me.
