### ISSUE TITLE
logo_dark.png not found in the URL

### ISSUE THREAD

**Issue by JamonBarns** [matterpoll/matterpoll#91]
The image cannot be found in the current URL, leading to the profile picture not showing properly.

**Comment by hanzei** [comment]
@JamonBarns Can you confirm that you using the newest version v0.1.0 of Matterpoll?

**Comment by hanzei** [comment]
@Spone What version of Matterpoll are you using?

**Comment by Spone** [comment]
v0.1.0 (I downloaded the latest version from this repo)

**Comment by hanzei** [comment]
What version of Mattermost Server are you running? Do you run you server under a subdomain like `chat.example.org`?

**Comment by hanzei** [comment]
Would you post the URL of your server here? Or PR me on http://pre-release.mattermost.com/? This would make testing easier.

**Comment by JamonBarns** [comment]
Hi hanzei thanks for your response, v0.10 as well and we use a subdomain

**Comment by kaakaa** [comment]
I would like to confirm how do you upload matterpoll plugin.

`logo_dark.png` isn't included in binaries for each platform (`plugin-darwin-amd64`, `plugin-linux-amd64` and `plugin-windows-amd64.exe`). `logo_dark.png` is in only `.tar.gz` file published in [releases page](https://github.com/matterpoll/matterpoll/releases).

So if you upload manually only binaries for each platform, `logo_dark.png` is missing. 
You might be enable to see `logo_dark.png` if you upload matterpoll plugin `.tar.gz` from system console.

https://github.com/matterpoll/matterpoll#installation
> 2. Upload this file in the Mattermost System Console > Plugins > Management page to install the plugin. To learn more about how to upload a plugin, see the documentation.

Is this for your case?


Additionally, 404 response might be affected by [cache](https://github.com/matterpoll/matterpoll/blob/master/server/plugin/api.go#L54). So when you set up matterpoll again, it had better to clear cache.

**Comment by geberl** [comment]
Just rechecked. I downloaded v1.0.1 from the releases page and uploaded it through Mattermost > System Console > Plugins > Management.

On my server the directory structure looks like that:

    $ tree /mattermost/plugins

    /mattermost/plugins
    `-- com.github.matterpoll.matterpoll
        |-- logo_dark.png
        |-- plugin.json
        `-- server
            `-- dist
                |-- plugin-darwin-amd64
                |-- plugin-linux-amd64
                `-- plugin-windows-amd64.exe

If I do `curl -v https://mattermost.mydomain.com/plugins/com.github.matterpoll.matterpoll/logo_dark.png`I get a **404**. In browsers (with cache cleared) the image also appears as a broken link.

Same result when trying via http without hitting our reverse proxy via `curl -v http://192.168.10.75:8065/plugins/com.github.matterpoll.matterpoll/logo_dark.png`:

    *   Trying 192.168.10.75...
    * TCP_NODELAY set
    * Connected to 192.168.10.75 (192.168.10.75) port 8065 (#0)
    > GET /plugins/com.github.matterpoll.matterpoll/logo_dark.png HTTP/1.1
    > Host: 192.168.10.75:8065
    > User-Agent: curl/7.54.0
    > Accept: */*
    >
    < HTTP/1.1 404 Not Found
    < Cache-Control: public, max-age=604800
    < Content-Type: text/plain; charset=utf-8
    < X-Content-Type-Options: nosniff
    < Date: Wed, 31 Oct 2018 11:41:01 GMT
    < Content-Length: 19
    <
    404 page not found
    * Connection #0 to host 192.168.10.75 left intact

A `curl -v https://mattermost.mydomain.com/plugins/com.github.matterpoll.matterpoll/` works, http **200** and output *Thanks for using Matterpoll v1.0.1*.

Are all the assets in the plugin's base dir served automatically by Mattermost?

No idea about Mattermost plugin architecture but what I see makes me doubt it ... I mean I also get an error 404 if I do `curl -v https://mattermost.mydomain.com/plugins/jira/plugin.yaml`although that file exists at `/mattermost/plugins/jira/plugin.yaml` on my server.

@hanzei @kaakaa Thanks for your work btw

**Comment by m49808** [comment]
Same issue. Uploaded via 1.0.1 via GUI and matterpoll bot icon is broken.

**Comment by hanzei** [comment]
@geberl Thank you for investigating into this!

> Are all the assets in the plugin's base dir served automatically by Mattermost?

No is not. But we have code to do so. See https://github.com/matterpoll/matterpoll/blob/master/server/plugin/api.go#L55.

What OS are you using for your Mattermost server? BTW are you using Docker?

There _might_ be a permission problem here. Mind checking this via `ls -l` /mattermost/plugins`?

**Comment by mindo** [comment]
We're also having this issue.
Unfortunately we're still using v0.1.0 because our Mattermost instance (v5.3.1) comes bundled with Gitlab and the plugin's newer versions do not support it.
We're also using a subdomain: mattermost.ourdomain.com.
The plugin was installed from the tgz and it includes the png file.
It did not have permissions to be readable by everybody. We changed the permissions but it still does not work.
Any pointers or any other test we can do to help debug this?

**Comment by geberl** [comment]
@hanzei I just went ahead and compiled the plugin myself for troubleshooting.

If I change line 18 in `api.go`from ...
`iconPath     = "plugins/" + PluginId + "/"`
to ...
`iconPath     = "/mattermost/plugins/" + PluginId + "/"`
the png gets served correctly. So I'm using a full path instead of a relative path.

Changed function:

	func (p *MatterpollPlugin) handleLogo(w http.ResponseWriter, r *http.Request) {
		ex, err := os.Executable()
		if err != nil {
			panic(err)
		}
		exPath := filepath.Dir(ex)

		w.Header().Set("Cache-Control", "public, max-age=604800")
		w.Header().Set("Geberl-Debug-One", iconPath+iconFilename)
		w.Header().Set("Geberl-Debug-Two", exPath)
		http.ServeFile(w, r, iconPath+iconFilename)
	}

Result of `curl -v http://192.168.10.75:8065/plugins/com.github.matterpoll.matterpoll/logo_dark.png`:

    *   Trying 192.168.10.75...
    * TCP_NODELAY set
    * Connected to 192.168.10.75 (192.168.10.75) port 8065 (#0)
    > GET /plugins/com.github.matterpoll.matterpoll/logo_dark.png HTTP/1.1
    > Host: 192.168.10.75:8065
    > User-Agent: curl/7.54.0
    > Accept: */*
    >
    < HTTP/1.1 200 OK
    < Accept-Ranges: bytes
    < Cache-Control: public, max-age=604800
    < Content-Length: 83921
    < Content-Type: image/png
    < Geberl-Debug-One: /mattermost/plugins/com.github.matterpoll.matterpoll/logo_dark.png
    < Geberl-Debug-Two: /mattermost/plugins/com.github.matterpoll.matterpoll/server/dist
    < Last-Modified: Wed, 31 Oct 2018 18:09:10 GMT
    < Date: Wed, 31 Oct 2018 18:09:17 GMT
    <
    {all that png data}

**Comment by hanzei** [comment]
@geberl Mind posting your docker file here or sending it to me on http://pre-release.mattermost.com? I suspect the exec path for your Mattermost server is not the same as usual.

**Comment by hanzei** [comment]
I think we got this figured you. Its is a problem with the working directory Mattermost runs in. This needs to be the `mattermost` directory. See the systemd file on https://docs.mattermost.com/install/install-ubuntu-1804.html#installing-mattermost-server for reverence.

@JamonBarns @Spone @mindo Mind checking your working directory for Mattermost? If you need help, you can PM me on https://pre-release.mattermost.com.

**Comment by m49808** [comment]
My working directory for mattermost is /opt/mattermost like the systemd file in the link you referenced. But I have data and plugins (and others) below that symlinked to an NFS mount for HA cluster reasons. Not sure i follow the post about the working directory. I'm not running docker, btw.

**Comment by mindo** [comment]
As I said before, our installation is part of Gitlab's installation package, so the working directory is `/var/opt/gitlab/mattermost`. I just symlinked that folder to mach the default value so the image can be found on the path `/opt/mattermost/plugins/com.github.matterpoll.matterpoll/logo_dark.png` but it still does not work.
I can checkout the code and compile myself, what should I change to make it work?

**Comment by geberl** [comment]
Can't we just get the called executable (eg `plugin-linux-amd64`) via `os.Executable()`, then go two levels up from wherever it's located to reliably get to `com.github.matterpoll.matterpoll`. Then maybe call `Abs`. Then join that path with `logo_dark.png` and return this?

This would make the plugin independent from how Mattermost was started and where it's located.

I can do a pull request but I don't know Go :)

**Comment by m49808** [comment]
> As I said before, our installation is part of Gitlab's installation package, so the working directory is `/var/opt/gitlab/mattermost`. I just symlinked that folder to mach the default value so the image can be found on the path `/opt/mattermost/plugins/com.github.matterpoll.matterpoll/logo_dark.png` but it still does not work.
> I can checkout the code and compile myself, what should I change to make it work?

In my case I had to create a plugins symlink within com.github.matterpoll.matterpoll/server/dist.

back to the plugins directory. Seems its looking for 
iconPath = "plugins/" + PluginId + "/"

and the starting point is dist in my case.

**Comment by mindo** [comment]
@m49808 do you mean something like this:
```
$ ls -l /var/opt/gitlab/mattermost/plugins/com.github.matterpoll.matterpoll/server/dist
total 55148
-rwxr-xr-x 1 mattermost mattermost 18797912 Oct 30 18:31 plugin-darwin-amd64
-rwxr-xr-x 1 mattermost mattermost 18990042 Oct 30 18:31 plugin-linux-amd64
lrwxrwxrwx 1 root       root             35 Nov  2 17:02 plugins -> /var/opt/gitlab/mattermost/plugins/
-rwxr-xr-x 1 mattermost mattermost 18674176 Oct 30 18:31 plugin-windows-amd64.exe
```
at least on my side it does not work :|

**Comment by hanzei** [comment]
First of all thank your very much for all the information you guys provided! I think this problem can be fixed in Matterpoll.  

>  Can't we just get the called executable (eg `plugin-linux-amd64`) via `os.Executable()`, then go two levels up from wherever it's located to reliably get to `com.github.matterpoll.matterpoll`. Then maybe call `Abs`. Then join that path with `logo_dark.png` and return this?

Pretty much this. If you want, you can work on this.

**Comment by m49808** [comment]
@mindo yes, exactly. that worked for me after a clear cache and reload in my desktop client. I'm not using gitlab though and paths are slightly different but same idea applies

**Comment by zetaab** [comment]
the symbolic link should be under mattermost server binary.

For instance we have mattermost server binary in
`/mattermost/bin/` folder. In this case it means that it will try to search plugins also from this folder. 
`/mattermost/bin/plugins/` however, our plugins is located `/mattermost/config/plugins`

I solved this by creating symbolic link in `/mattermost/bin` folder:

`ln -s /mattermost/config/plugins plugins`

**Comment by kaakaa** [comment]
@mindo 
As default settings, GitLab Mattermost seems to use `/opt/gitlab/embedded/service/mattermost` as working directory. (`/var/opt/gitlab/mattermost` is used for storing user data.)
So if you create symbolic link in `/opt/gitlab/embedded/service/mattermost`, you may be able to see logo_dark.png.

```
ln -s /var/opt/gitlab/mattermost/plugins /opt/gitlab/embedded/service/mattermost/plugins
```

@zetaab 
Thank you for your PR. It looks good. I'll take a look in more details.

**Comment by hanzei** [comment]
I don't think creating symlinks is the right treatment for this issue. It is a bug in Matterpoll and should be fixed there. We will get a fix merged and a patch release cut this week.

**Comment by kaakaa** [comment]
Yes, I agree with you. Creating symlinks is just work around. We must fix this bug.

**Comment by mindo** [comment]
@kaakaa Yes, that symbolic link sorts it out for us.
@hanzei I totally agree, but unfortunately _Matterpoll_ no longer supports the _Mattermost_ version that comes bundled with _Gitlab_ so having a workaround is most welcomed :)

**Comment by hanzei** [comment]
v1.0.2 got releases which fixed this bug
