### ISSUE TITLE
--progress not working

### ISSUE THREAD

**Issue by JtheBAB** [matterpoll/matterpoll#92]
Hi

When i try `/poll "Is Matterpoll great?" "Of course" "In any case" "Definitely" --progress`

i get this:

![progress](https://user-images.githubusercontent.com/42135332/47552128-41182c80-d904-11e8-97e2-54dcec721c0d.png)

Matterpoll 0.1.0
Mattermost 5.4.0

Best regards

JtheBAB

**Comment by hanzei** [comment]
Poll Settings are currently only available on `master` and not on Matterpoll v0.1.0. We will cut v1.0.0 soon ™, which will include Poll Settings.
