### ISSUE TITLE
Show how voted during poll via Poll Setting

### ISSUE THREAD

**Issue by JtheBAB** [matterpoll/matterpoll#96]
Hi

My users ask me if it would be possible to see how voted for which answer when the poll is active. At the moment there is "just" the numbers per answer visible.

Best regards

JtheBAB

**Comment by hanzei** [comment]
While I see the positive sides of such Poll Setting, the UX can be tricky. How would you such information?
Currently if you use `progress` the number of people is shown in the button. Would you also show the usernames there?

**Comment by lkraav** [comment]
> Currently if you use progress the number of people is shown in the button. Would you also show the usernames there?

@hanzei probably yes.

For scheduling "poll" use cases, ere's a screenshot example of a display format that really works well (from doodle.com). Obviously this exact fidelity level is probably out of reach here, at least to start, but perhaps there's a "barebones" way of achieving a similarly understandable display of poll results.

![image](https://user-images.githubusercontent.com/147228/47748443-82f1fb80-dc93-11e8-8ae0-15f9f242817e.png)

**Comment by JtheBAB** [comment]
I think in the button it will make the button to big when many people are voting. Maybe like the result but „just“ dynamic.

**Comment by piotr-wegert** [comment]
It would be very nice to have this option. One of our use cases Slack before we switched to MM was to start a poll about who wants to go on which conference (with voting on multiple options allowed). 

The main benefit was that folks could see who is going where and make their decision based on that.

**Comment by deedubdevs** [comment]
@hanzei Usernames don't need to be on the button. [Simple poll](https://simplepoll.rocks/) for slack did it in a functional way. 
[Video example](https://simplepoll.rocks/static/main/images/new-landing-page/basic-poll-voting.ca4162c5a9a2.webm)

**Comment by hanzei** [comment]
> @hanzei Usernames don't need to be on the button. [Simple poll](https://simplepoll.rocks/) for slack did it in a functional way.
> [Video example](https://simplepoll.rocks/static/main/images/new-landing-page/basic-poll-voting.ca4162c5a9a2.webm)

I know simple poll. But they use a different approach with answer options not in the  buttons, which I don't like. I'm still looking for a design that keeps the answer options in the buttons. The responses can be outside of the buttons IMO.

**Comment by hanzei** [comment]
Idea: Add "Show current results" button that shows the current list of votes in a modal.

**Comment by mjnaderi** [comment]
@hanzei Any progress on this? I found https://github.com/M-Mueller/mattermost-poll but it's hard to setup. It would be very good if matterpoll had the features of M-Mueller/mattermost-poll.

- `--public`: show who voted during poll and after poll is closed
- `--votes=n`: allow each user vote for n options
- `--bars`: with --bars, names of voters can be displayed under the bars

**Comment by mjnaderi** [comment]
Also, options can have a maximum *capacity*. Something like this:

    /poll "Pick a time" "09:00-10:00",2 "10:00-10:30",1 "10:30-11:00",1

Only 2 users can vote for `09:00-10:00`, and only 1 user can vote for each of other options.

**Comment by mjnaderi** [comment]
> > Also, it would be so good if poll options could have an optional _capacity_. Something like this:
> > ```
> > /poll "Pick a time interval" "09:00-10:00",2 "10:00-10:30",1 "10:30-11:00",1 --limit=1
> > ```
> > 
> > 
> > So only 2 users can vote for `09:00-10:00`, and only 1 user can vote for each of other options. And each user can only vote for 1 option.
> 
> @mjnaderi Would you please open a new issue for this idea?

Sure. I created #287.

**Comment by hanzei** [comment]
I did experiment with the post card feature, which allows integration to add additional information to a post, which would then be shown in the RHS after clicking on a little `i`.

![Screenshot from 2020-04-25 19-54-04](https://user-images.githubusercontent.com/16541325/80865333-ff9ad700-8c88-11ea-8435-36cba03c493f.png)


cc @kaakaa

**Comment by hanzei** [comment]
I've pushed by first prototype to `96_cards`. If someone picks it would and drives it to completion, that would be great.

**Comment by savegame** [comment]
while matterpoll dont show votes during poll, we are use reactions for this
![изображение](https://user-images.githubusercontent.com/16311332/121671443-3449a680-cab7-11eb-9032-1280ec283735.png)

the example in the picture is not quite good, very similar to each other emoji, but the point is clear

**Comment by nicolas-goudry** [comment]
@hanzei One year later, could you please give us an ETA on this feature request? Thanks :slightly_smiling_face:

**Comment by hanzei** [comment]
@nicolas-goudry There won't be any ETA for feature requests. If someone wants to pickup this ticket and work on it, it would be highly appreciated.

**Comment by jbattistispiria** [comment]
@kaakaa @hanzei I would like to take this one. I'm going to continue with what was done in [`96_cards`](https://github.com/matterpoll/matterpoll/tree/96_cards) branch.
